### ISSUE TITLE
TermHub: Sharing `ConceptMap`s with mapping commons

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#101]
Mirror of: https://github.com/jhu-bids/termhub-csets/issues/2

**Comment by hugwuoke** [comment]
I'm a bit confused as to why both this issue and it's mirror are needed.

**Comment by joeflack4** [comment]
@hugwuoke Hmm, I think you might be right. Normally mirror issues like this are useful when there is no shared project board. But `termhub-csets` does have access to that board, and it's already there. I marked it with low urgency. Anyway I agree; closing this.
