### ISSUE TITLE
TermHub: Stateful URLs

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#102]
## Overview
We don't just want a URL to every route/page, but also more custom URLs that link to a specific application state at a given route.

I think it is likely that this customization will take place as URL query params, rather than path params, e.g. `http://path/to/route?queryParam1=val1&queryParam2=val2`

**Things to think about**
Some of the query params will reflect params that are passed to the API to fetch specific data, but some of them will also be for application state, e.g. something like `selected=<conceptSetId1>&selected=<conceptSetId2>&selected=<conceptSetId3>` for a state where we have 3 concept sets that are selected in the UI.

**Comment by Sigfried** [comment]
This is working now for multiple codesetIds. Might want to revisit if more functionality is needed, but it's good for now.
