### ISSUE TITLE
TermHub: Utilize RxNorm API

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#104]
## Overview
This is just a placeholder. I think that this needs to be added to an existing issue, but I'm not yet sure how which TermHub feature would utilize the RxNorm API.

### Useful links
1. [RxNorm REST API](https://lhncbc.nlm.nih.gov/RxNav/APIs/RxNormAPIs.html)

### Conversation context
_BIDS teams chat_

[9:13 AM] Davera Gabriel
Harold Lehmann  the workflow in that document is using an instance of Atlas... but this could be configured otherwise with the new Enclave functionality.  RxClass can be queried via the REST API.  This document has some scratch API calls I built while we were working on the medication concept sets before: https://docs.google.com/document/d/1yCg9jVejKyvQEBJgRJwj-_uWIx56JyrSa0VzTbO2Or8/edit
what would be truly innovative / slick would be to be able to interrogate the RxNorm REST API int the "outside the enclave" array of functions as a stage to concept set import

[9:15 AM] Harold Lehmann
Davera Gabriel -- many thanks. I agree with the "outside the Enclave" idea...let's put it on the feature-request list

[9:29 AM] Davera Gabriel
@Joe: I think something along the lines of a header which works a queue of desires queries, the fulfillment of those queries. They can be retained and reused later
you have to study how they (NLM) have constructed the content - so there's some work there... Also know that RxClass is different but related to RxNorm

[9:34 AM] Davera Gabriel
there is also a SQL-enabled way to access this info.  Its just for me the REST API seemed simpler

**Comment by hugwuoke** [comment]
Since we have Rx norm in Term Hub is this closable or is it deeper than that?

**Comment by joeflack4** [comment]
@hugwuoke Good catch. Actually I'm not sure: @Sigfried We decided not to use the RxNorm API. Is this a permanent decision, or something we'll revisit in the future? I'm gonna close this issue for now but feel free to re-open.
