### ISSUE TITLE
Related Csets Table. Was: Prompt or auto-add overlapping concept sets instead of having user select every cset by name

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#118]
Interface ideas from e6b34a3:

  - cset search will now only occur on the cset search page. you choose
    csets there and navigate to CSet Comparison and see them all
    compared there.
  - a handlful of cset cards now fit on the screen comfortably
  - interface could change by
    - [x] #133
    - [ ] #134
    - [x] #135
    - [x] #136
    - displaying table of all related csets (118) and allowing them
      to be added by clicking there

Relevant changes from e6b34a3:

    - fixed card width and height and allowed flex wrapping.
    - removed CsetSearch from CsetComparisonPage
    - refactored into a hierarchy of small utility components to allow
      state and data to be passed down to page components without global
      state and stuff. this should be easier to understand and maintain:

        <BrowserRouter>                     // from index.js root.render
            <QCProvider>                    // all descendent components will be able to call useQuery
                <QueryStringStateMgr>       // gets state (codeset_ids for now) from query string, passes down through props
                    <DataContainer>         // fetches data from cr-hierarchy
                        <CsetsRoutes>       // where routes are defined (used to be directly in BrowserRouter in index.js
                            <App>           // all routes start with App
                                <Outlet/>   // this is where route content goes, all the other components
                            </App>
                        </CsetsRoutes>
                    </DataContainer>
                <QueryStringStateMgr>
            </QCProvider />
        </BrowserRouter>

**Comment by Sigfried** [comment]
9a55f4a1a65be53fca6731dec852f07eec6adb25 got the data in place to do something with this

**Comment by joeflack4** [comment]
That is actually a really good idea!
