### ISSUE TITLE
Distinguish intensional/extensional concepts in cset display

### ISSUE THREAD

**Issue by Leskena2** [jhu-bids/TermHub#121]
Distinguish in concept hierarchy between version item (explicitly included) concepts (hmm, has to be for each cset) and concepts included by expanding to descendants, mapto,...    might not be too difficult: join concept_set_member concept to version_item, color those rows, and show flags

**Standard vs. non-standard code display** (is this different from above?)

**Comment by joeflack4** [comment]
@Sigfried Marking this completed; over a year ago I think.
