### ISSUE TITLE
Include codeset ids in url when navigating between pages that have codeset ids

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#128]
It's just CSet Search and CSet Comparison at this point, and, at this point, CSet Search isn't useful, but it might be ...

Combine this with #122?

**Comment by joeflack4** [comment]
Yeah, I guess a lower priority until we hear of more demand for the cset search page.

I think this makes sense to do, and could knock out #122 at the same time. All I was thinking for that issue was to make the search bar wider.

**Comment by Sigfried** [comment]
Actually, already took care of this in e0dff66. Felt like I needed to handle it before tackling #118.
