### ISSUE TITLE
adding [x] to corner of cset card to remove

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#134]

**Comment by joeflack4** [comment]
Just verifying myself as well. I haven't had the opportunity to use the TermHub frontend recently, but man it's starting to look / feel great!
<img width="608" alt="Screen Shot 2023-06-15 at 5 00 25 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/24f61ffb-bb64-4cac-b38d-48208bf8e27e">
<img width="1298" alt="Screen Shot 2023-06-15 at 5 00 31 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/4b4a1bfb-6626-46be-a275-20b928a9ab9b">
