### ISSUE TITLE
Need to expand concept subset in datasets.py

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#141]
Having problems with missing concepts and missing links between concepts... can explain later.

What I think we should do is expand the subset of concepts in prepped files to: all of the concepts appear in the concept_ancestor table where either the ancestor_concept_id or the descendant_concept_id is included in the concept_set_members table. Right

**Comment by joeflack4** [comment]
Makes sense to me so far! Will learn more later on.

**Comment by Sigfried** [comment]
Weird: out of 78,558,033 rows in the concept_ancestor table, 22% of the ancestor_concept_ids are in concept_set_members (what we're saving now), but 61% of descendant_concept_ids are. At that point, maybe it's not worth filtering it at all.

**Comment by Sigfried** [comment]
fixed earlier
