### ISSUE TITLE
User interface for data inventory, browsing, (modifying and saving), and uploading

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#147]
## Overview
Perhaps could begin with introspection-driven browsing of `ds` (variable that stores datasets) and `dsi` (datasets filtered by selected codesets) in `app.py`. 

- [x] #165
 
## Sub-tasks
1. Make a new page:
  Show what is useful info. Perhaps just show a comment about what the property is, maybe n records. Show the columns in these dataset. And show a table showing at least the first few rows. H1 for i and ii. H2 for each dataset name.
  i. Shows all the global stuff in `ds` (all the datasets; not the functions). The idea is that we show provenance, what data is accessible.
  ii. Show `dsi` as well. What's accessible for concept sets selected.
- [x] #156
- [x] #230

## Related
1. #142 
8. #143 
9. #146 
10. #42

**Comment by Sigfried** [comment]
- [ ] Allow cset modification from the ConceptSetComparison table -- just the ability to add and remove concepts from existing concept sets.

**Comment by hugwuoke** [comment]
@Sigfried tasks seem completed so seems safe to close.
