### ISSUE TITLE
handle overlarge request

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#149]
This url is taking forever to run:

http://127.0.0.1:8000/new-hierarchy-stuff?rec_format=flat&codeset_id=400614256|419757429|484619125|573795|692562246|748757884|879212923

Set breakpoint (long into the interminable request processing) at the first statement in `nested_list` and saw it was at level 7 and 400K lines.

**Comment by joeflack4** [comment]
Oh, wow, I wonder if there's anything else that we can cache to help w/ this, but I would guess that our algorithm probably needs performance tweaking as well.

**Comment by hugwuoke** [comment]
@Sigfried I'm closing this because TermHub has changed a lot since October so this error is probably no longer relevant.
