### ISSUE TITLE
Allow cset modification from the ComparisonDataTable -- just the ability to add and remove concepts from existing concept sets.

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#156]
This would probably be the quickest way to make TermHub useful. I (Siggie) met with Kim Murray 2022-10-07 and she has a definite and ongoing need for comparing csets and making changes to them.

**Comment by Sigfried** [comment]
Commit 602f9d1 provides checkboxes in ComparisonDataTable and a stub function in app.py for registering modification requests. @joeflack4 we can talk about how to implement these. But we'll need access to uploading to enclave, which we're also waiting for for #148.

**Comment by joeflack4** [comment]
Really glad to hear that someone (Kim) has an immediate use for this! Can talk about this on Wednesday.

**Comment by hugwuoke** [comment]
@Sigfried  I believe this feature is now working.
