### ISSUE TITLE
Unit testing framework for react and for py/fastapi

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#160]
At least one test for each, just so that we have a starting place.

## Subtasks
- [x] 1. Python
- [x] 2. JS / React
- [x] System for tracking what tests need to be written / have been written / ...
  - Like other planning, raises question: track it just using statuses or labels, or also/instead using larger tickets with subtasks?
  - Possibly: Log a ticket for a bug, mark it, if desired, as also requiring a unit test. So, two tickets -- one for bug, one for test? or require test to be written before bug ticket can be closed?

**Comment by joeflack4** [comment]
I'm not sure what to pick for react. I think I've only written unit tests in `node` for JS before. For Python there's various options, but I've always been fine w/ the standard library's `unittest`.

**Comment by Sigfried** [comment]
There's stuff about writing/running tests for create-react-app here: https://create-react-app.dev/docs/running-tests/

I also noticed a couple of possibly relevant files in src generated by create-react-app: `setupTests.js` and `reportWebVitals.js`. I don't know anything about them, but they might be worth looking into.

**Comment by Sigfried** [comment]
The bug that inspired the impulse to start unit testing was this: 

![Image](https://user-images.githubusercontent.com/1586931/195596832-856c3808-9731-4ffd-b325-600036414442.png)

Part of what should happen under this ticket, beyond establishing a few initial tests, is deciding how to track tests. I'll add it to the subtasks.
