### ISSUE TITLE
Fix precision/recall formatting. Add explanation as tooltip/mouseover

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#162]

**Comment by Sigfried** [comment]
@joeflack4 -- Did you point me towards https://floating-ui.com/ for tooltips? It's powerful but not super easy to understand -- AND it's written in typescript. I was able to translate typescript example code to javascript and the tooltips work, but I just saw that the jest test runner doesn't like it. I think maybe mixing typescript and javascript sources can be problematic. Maybe it's ok to use js if the whole project is converted to ts, but it's not ok to use ts while the whole project is configured for js.

More info: https://create-react-app.dev/docs/adding-typescript/

So -- should we do that and keep floating-ui or swap out for a different tooltip library?

**Comment by joeflack4** [comment]
@Sigfried I linked something else I'm pretty sure. I think there are probably a lot of options for tooltips. I agree that using the one that is quickest / has least friction is probably the best option, so that means probably not https://floating-ui.com/.
