### ISSUE TITLE
Modify/create cset locally and upload to enclave

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#165]
### Updating an existing cset
1. Frontend: User clicks on header / button to edit concept set.
2. Frontend: reacts to click
~a. Frontend: They get a page which shows: (i) list of concept names~ (can do this in the future)
b. Frontend: A new column.
3. Frontend: The label should say (draft) instead of (v#). The user can check/uncheck the concepts they want / don't want
4. Frontend: They click a button to 'commit changes'
  a. Will need their user RID in order to set the created_by fields for concept_set_container and code_set
  b. What other metadata do we need (for MVP)?
6. Backend: Hit route (new route?)
7. Backend: Persist changes (multiple files? which files?)
  a. Persist by writing to prepped files? yes...and maybe use git diff and patch
9.  Backend: Push to enclave?
10. Frontend: User sees confirmation message that commit succeeded?

### Creating a new cset
TODO

## Concerns
1. How to handle production server updates to `termhub-csets` vs local deveopment?
- Maybe have them commit to different branches, e.g. if `env` variable is `production`, commit to `main`, else `develop`.

**Comment by joeflack4** [comment]
In regards to _persist changes_, if we do indeed update the `prepped_files/` with the draft changes from the user, we don't want to overwrite those changes by a new run of `enclave_wrangler` dataset download / transform.

**Comment by joeflack4** [comment]
Example URL for local testing: http://localhost:8000/update-cset-concept-inclusion?codeset_id=496860542&concept_ids=35787839&concept_ids=35787840

**Comment by joeflack4** [comment]
## Upload to enclave && frontend callback
another idea i had. this will be among the last things i would do on this issue. but we should have a callback URL on the frontend for notifications

and we can put the code to display a bootstrap / material notification or whatever near the root of the frontend layout

the idea is that we would persist changes locally, then async try to upload to the enclave. and then when done, hit the frontend callback url with the result message
