### ISSUE TITLE
Bug: New enclave API: Failed validations

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#168]
## Overview
Mostly, things with the new API have been working good so far. However, I haven't figured out some of the parameters. I think I'm either (a) passing the wrong data type / structure, or (b) I'm passing the param correctly, but due to some issue, the API is returning an error instead of a message detailing the validation issue (e.g. perhaps it needs to find a reference to some object that does not exist). @Amin: I think that by design, validate is supposed to return a 200 OK, with an explanation of anything that is invalid, so I added a part (2) for you guys to address on your guys' end when you have the time.

## Things to solve
- [x] 1. TermHub end: Learn what we need to do to get this to work, and fix our code.
  - [x] 1.1. `create-new-draft-omop-concept-set-version` param: `conceptSet`
  - [x] 1.2. `create-new-draft-omop-concept-set-version` param: `baseVersion`
  - [x] 1.3. `create-new-concept-set` user params
  - [ ] 1.4 `set-omop-concept-set-version-item` param: `concept-set-version-item`
- [ ] 2. Enclave end: Return HTTP `200` responses with informative validation information for failed param as well as all normal validation information for other params

### Failure 1 of 2: conceptSet (OntologyObject)
I passed `"conceptSet": "x"`, but I'm not sure what to pass.

#### Request: curl
```sh
curl -H "Content-type: application/json" -H "Authorization: Bearer $TOKEN" https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/create-new-draft-omop-concept-set-version/validate --data '{"parameters": {"conceptSet": "x", "intention": "x", "domain-team": "x", "provenance": "x", "current-max-version": 2.1, "annotation": "x", "limitations": "x", "intended-research-project": "x", "versionId": 1, "authority": "x"}}' | jq
```

#### Response: Error code
`500`: internal server error

#### Response: curl
```sh
{
  "errorCode": "INTERNAL",
  "errorName": "Default:Internal",
  "errorInstanceId": "f5134f0c-375b-4bac-abf3-d692dec1fb69",
  "parameters": {}
}
```

#### Request
```sh
curl -H "Content-type: application/json" -H "Authorization: Bearer $TOKEN" https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/create-new-draft-omop-concept-set-version/validate --data '{"parameters": {"intention": "x", "domain-team": "x", "provenance": "x", "current-max-version": 2.1, "annotation": "x", "limitations": "x", "baseVersion": "x", "intended-research-project": "x", "versionId": 1, "authority": "x"}}' | jq
```

#### Response: Error code
`404`: not found

#### Response
```sh
{
  "errorCode": "NOT_FOUND",
  "errorName": "ActionParameterObjectNotFound",
  "errorInstanceId": "7074e218-8280-4519-a6a4-4a753cd240da",
  "parameters": {
    "parameterId": "baseVersion"
  }
}
```

## Failed requests: `create-new-concept-set`
For this one, I know what to do. I'm getting this for params `assigned_sme` and `assigned_informatician`, but I know that I can fix this by solving `InvalidUserId`. However, ideally I'd ideally still like to get a non-400 response that includes validation information for other params.
```sh
{'errorCode': 'INVALID_ARGUMENT', 'errorName': 'InvalidUserId', 'errorInstanceId': 'd92f54bd-2f77-4752-8fcf-faf2464f4b55', 'parameters': {'userId': 'x'}}
```

## Failed requests: `set-omop-concept-set-version-item`
Don't have time to show the `curl` for this one right now, but I'm not sure what to pass for the `concept_set_version_item` param. 

Here's the docs for it:
```
"concept-set-version-item": {
            "description": "",
            "baseType": "OntologyObject"
}
```

Here's the error I'm getting (I believe this happens only on `/apply`, whereas `/validate` is fine):
```
Unexpected <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/set-omop-concept-set-version-item/apply
```

#### Request: curl
```sh
curl -H "Content-type: application/json" -H "Authorization: Bearer $TOKEN" https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/create-new-draft-omop-concept-set-version/validate --data '{"parameters": {"intention": "x", "domain-team": "x", "provenance": "x", "current-max-version": 2.1, "annotation": "x", "limitations": "x", "intended-research-project": "x", "versionId": 1, "authority": "x"}}' | jq
```

#### Response (truncated)
```sh
{
  "result": "INVALID",
  "submissionCriteria": [],
  "parameters": {
    "domain-team": {
      "result": "VALID",
      "evaluatedConstraints": [
        {
          "type": "objectQueryResult"
        }
      ],
      "required": false
    },
...
}
```

**Comment by Sigfried** [comment]
This fixes the last of the errors Joe detailed above:

    curl -H "Content-type: application/json" -H "Authorization: Bearer $TOKEN" https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/create-new-draft-omop-concept-set-version/validate --data '{"parameters": {"intention": "x", "domain-team": "x", "provenance": "x", "current-max-version": 2.1, "annotation": "x", "limitations": "x", "intended-research-project": "x", "versionId": 1, "authority": "x", "intended-research-project":"RP-4A9E27","conceptSet":"testing container creation from api",  "current-max-version":null}}' | jq

**Comment by joeflack4** [comment]
Closing for now since this is working on our end, and the issue is with the enclave. But if we do need to use a different endpoint and haven't figured out which params to use and how, we can re-open this.
