### ISSUE TITLE
Performance: Browser caching & global state

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#169]
## Overview
We want front-end experience to be fast, and we don't want to make repeated, unnecessary requests.

## Options
Can do one or all of the following
- [ ] 1. Global state for a given user session
- [ ] 2. Browser caching (for multiple user sessions on same machine)

**Comment by Sigfried** [comment]
@joeflack4: Can you explain what you mean by option 1, global state for a given user session? Is it the same idea as the second option except using `window.sessionStorage` instead of `window.localStorage`?

**Comment by joeflack4** [comment]
@Sigfried I don't know if sessionStorage and localStorage store on disk or in memory. But what I mean by global state is React state management at the global level, e.g. Redux.

**Comment by Sigfried** [comment]
Hmm... Maybe we do need to think about global react state via something like `Redux`, but I've been leaning away from that sort of thing for now and managing all the `querystring` and fetched data state in `App.js` and sending props to components that need them. Have been spending (a lot) more time than I'd like on code to refresh components and calculated objects without excessive re-rendering. Maybe a solution that manages `window.localStorage` or `window.indexedDB`` would help with that -- not sure -- but would certainly help with caching. For our purposes and the large amount of data we'd like to cache, `indexedDB` would be better than localStorage, but it's supposed to be quite a pain to use. I've started looking into wrappers like [Dexie](https://dexie.org/), but deciding on one and implementing is is a significant time investment, too. Dexie might make it easy to interact with local cached data, but they want to sell you a cloud server solution and don't make it obvious how to sync with a database or rest server.

**Comment by Sigfried** [comment]
Fixed (to some degree) by using persistent storage with react-query.
