### ISSUE TITLE
Future: Graph-based backend

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#170]
## Overview
@mellybelly and @Sigfried had [a discussion](https://tims-4sl3026.slack.com/archives/C02V4C75NV8/p1666369930558969) about a future potential backend for TermHub. Currently, we're using a flat-file store that is based on OMOP. We've been considering moving the primary backend to FHIR, or perhaps using that backend for alternative features. Another option is a graph database as a backend. This has several advantages: (i) being a highly normalized, large, interconnected data structure, it can support very sophisticated queries, so is very flexible, (ii) can do typically requires several queries in a single query, (iii) easy integration with biomedical ontologies and other data in formats like OWL and RDF.

## Options
1. [TCCM](https://github.com/HOT-Ecosystem/tccm-api): One option is to continue development on TCCM, which already has a Neo4J graph DB backend, and already has a lot of code written out, e.g. loaders for some ontologies and REST endpoints.
2. [TriplyDB](https://triplydb.com/): May be able to use this as a free option, combine multiple RDF files, and upload them here.
3. OAK
4. Gremlin (JanusGraph)
5. Gremlin (Neo4J)
6. Cypher (Neo4J)

**Comment by hugwuoke** [comment]
After I feel the project issues and board is organized with milestones etc I plan to go through the backend more thoroughly on Siggie's request to clear redundant functions etc. I was wondering if I should figure out what this is referring to incase this is relevant for that upcoming work.

**Comment by joeflack4** [comment]
@hugwuoke I think you don't need to worry too much about this one. I just added this to the TIMS (Terminology Infrastructure Management Services) grouping issue (#263). 

The crux of it is that graph databases allow you to do cool things that you are hard to do with traditional relational databases (e.g. PostgreSQL). There are some features we'd like to add to TermHub that would be better suited for a graph database.

Presently, I've been working on a graph-based backend/db ([OAK](https://github.com/INCATools/ontology-access-kit)), albeit not a full fledged graph DB (e.g. Neo4J) as part of my work for the TIMS team. That backend will be shared between TermHub and TIMS, but it's not robust enough to do everything that we'd like from a full fledged DB. Another member of the TIMS team, though, is getting started on a full fledged database, and Siggie and I may contribute to that as well. It's possible we may have something here to use in the next couple months, but it also could take a while longer.

When it's ready for us to use, though, we might actually want to just close this issue and make new issues describing what kind of features, refactoring, etc, we'd want to do.

**Comment by joeflack4** [comment]
I take it this is replaced by #528?
