### ISSUE TITLE
nested concept expand is broken (fixed 2022-11-11, except for UI issues)

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#173]

**Comment by Sigfried** [comment]
e7730f9 fixes the brokenness of this, but the UI still sucks. But fixing the UI -- with better handling of nested row expand/collapse so it's clear what's happening -- is not easy. I don't know if react-data-table can do it nicely without a ton of work. So, placing this in backlog/todo for now.

**Comment by hugwuoke** [comment]
@Sigfried closing because the only collapse/expand I know about is on the hierarchy and that is fixed, feel free to reopen if I'm mistaken.
