### ISSUE TITLE
Report data counts

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#174]
Cset comparison page, the line where it talks about stats, insert a link to a new page with a table. Create new page with table to show counts.

**Comment by Sigfried** [comment]
@joeflack4 -- I'm unclear what counts (or anything else) should be on this new page

**Comment by joeflack4** [comment]
@Sigfried This is from November 2022. Seems to be very early discussions about patient/record counts. If I recall correctly, this was the initial implementation we had thought about / discussed at the LL meetings. But we have a different implementation now, so I think we should close this!
