### ISSUE TITLE
Streamline backend data model: downloads, transformations, relationships

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#177]
## Overview
We have a lot of data saved, but no cohesive data model. We don't have the data normalized yet. We should decouple `enclave_wrangler` and `termhub` code that is tightly coupled to dataset download and transformations. This may involve something like a DAG to specify the flow of downloads and transformations, or it might not. My basic thought is that we will want to (i) specify the data that we want, (ii) be able to run a job that fetches and transforms and satisfies all those requirements, (iii) `enclave_wrangler` and `termhub` should request data that is already transformed and cached, and, if any of that hasn't been done yet, the job to do so will be run at that time.

<img width="537" alt="Screen Shot 2022-11-07 at 4 03 15 PM" src="https://user-images.githubusercontent.com/13045020/200414916-12021367-3eaa-4214-91bc-e0a2f648da9a.png">

[termub - data model and flow.pptx](https://github.com/jhu-bids/TermHub/files/9955434/termub.-.data.model.and.flow.pptx)

## Related
- #143
- #175 
- #176
- #178

**Comment by hugwuoke** [comment]
Hmm I think we currently have a vision and organization structure.

**Comment by joeflack4** [comment]
Oh yeah, this was before we even had a PostgreSQL DB. I'm so glad we took the time to make that change.
