### ISSUE TITLE
CRUD: CSV Bulk upload

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#178]
## Overview
We want to 
- [ ] #181
- [ ] #213 - (ii) create container: an entirely new concept set (with metadata, e.g. researcher), 
- [ ] (iii) edit metadata for existing concept sets (can't be done on existing version), 

## Subtask list
Haven't yet thought through the work that needs to be done on frontend/backend to meet the requirements above.
- [ ] 1. Backend
- [ ] 2. Frontend

## Related
- #147

**Comment by Sigfried** [comment]
@joeflack4: Is this different from #181? Does it need its own issue?

**Comment by joeflack4** [comment]
@Sigfried I've decided you're right and that this is redundant. Take a look at the updates I've to the [concept set version](https://github.com/jhu-bids/TermHub/issues/181) issue, and I also created [an issue for container](https://github.com/jhu-bids/TermHub/issues/213).
