### ISSUE TITLE
problem with checkboxes on rows in ComparisonDataTable

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#191]
Getting errors with codeset_id 419757429, which is currently included in the Example Comparison set of cset ids. Need to figure out why. This is occurring in both the develop branch and the db branch. I don't remember it being an issue before we switched to working on the db branch, so maybe the problem is arising from some change in the data rather than a problem with code. Or maybe if we go to an older commit on the development branch the problem will disappear.

**Comment by Sigfried** [comment]
Oh -- indeed. When I go back to e3373ebf, the problem goes away. Guess I'll try to narrow it down.

**Comment by Sigfried** [comment]
Ok -- when I go back to 899ebb39 in October, the problem goes away. Will try to place the change where it started.

**Comment by Sigfried** [comment]
Hmm... maybe 7a2b9bf didn't entirely fix the problem. These messages went away for some reason briefly, but after I reloaded everything (I guess) they came back:
![Screen Shot 2022-12-21 at 9 21 25 AM](https://user-images.githubusercontent.com/1586931/208927150-f5594f9d-4736-4bf2-bce6-9ebefcc90651.png)

**Comment by joeflack4** [comment]
Concept with ID `256716` is problematic.
Why is it problematic?
We looked at its appearances in the old cr-hierarchy JSON we saved as a static file and are returning, and the new cr-hierarchy. But in the instances where it appears, it's the same structure in both.
