### ISSUE TITLE
Add documentation and/or documentation links to TermHub. Especially: link to github issues

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#198]
## Sub tasks
- [x] Complete initial page
- [ ] Siggie to review with Lisa

### Where
a. About page
b. A menu icon/option for 'ask for help', or 'log problem'?

### What
For sure:
- link to issues (this means we need issue pre-formatting, like commented sections like 'expected behavior', 'actual behavior', 'summary', 'versions', etc)
Maybe:
- info about each page?
- link to CSV format?

## What we have now
<img width="1055" alt="Screen Shot 2023-01-11 at 1 06 05 PM" src="https://user-images.githubusercontent.com/13045020/211883965-552e4b21-96a7-43e6-af12-5ff89f1b89d3.png">

**Comment by Sigfried** [comment]
Add link to [community call demo](https://youtu.be/EAwBZUiNUUk?t=2130)

**Comment by joeflack4** [comment]
added a link

**Comment by hugwuoke** [comment]
@Sigfried I see all these features in TermHub now so I'll close this issue.
