### ISSUE TITLE
Bug: Only caching some `codeset_ids`

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#199]
Fix bizarre caching problem where it only caches a couple of specific sets of codeset_ids

**Comment by Sigfried** [comment]
Fixed this -- **I thought** -- by switching the localStoragePersister used by persistQueryClient. But the problem just started happening again and wouldn't go away when I checked out older commits or restarted browser, etc.. I tried `localStorage.clear()` in the console, and that fixed it. So, maybe we need to force that to happen every so often.

**Comment by joeflack4** [comment]
@Sigfried Do you think this problem has went away?
