### ISSUE TITLE
Why are researchers missing from data?

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#202]
For instance, [this person](https://unite.nih.gov/workspace/hubble/exploration/autosaved/985f2e33-dece-47a0-9918-a97968e2b302_S7%2BlotabIwxZ_0?objectId=ri.phonograph2-objects.main.object.54ec8821-a025-41a4-b755-5c06242bbb0e) is the `created_by` of a [code set](https://unite.nih.gov/workspace/hubble/objects/ri.phonograph2-objects.main.object.03e3a846-f83f-4e61-83f0-87a3213e53e3), but doesn't appear in the researchers table.

**Comment by joeflack4** [comment]
This may just require updating the database.
