### ISSUE TITLE
Add: Regular database refreshes/updates using `datasets` API

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#207]
## Overview
The enclave changes very frequently. We need a way to update TermHub's database to reflect the current state of the enclave for the tables we're downloading/syncing.

**Important**: This is related to #189, only that issue uses `objects` and this one uses `datasets`.

## Sub tasks
- [ ] Finish setting up
- [ ] Docs: docs/developer.md

## Options
We should probably implement both (a) and (b) eventually.
### a. Regular updates
I like 'a.c' the most.
(a.a) a cronjob or whatever the equivalent is for that in our Azure setup, or 
(a.b) we could set up a worker process in uvicorn/gunicorn and either keep that process alive and do things on a schedule, similar to a cronjob, or have the web server keep track of the schedule perhaps and send the request to the worker.
(a.c) Mike recommended: GitHub workflow and use the schedule trigger type

### b. On trigger
**i. What to fetch**
(b.i.a) only what a user may have updated using TermHub, or 
(b.i.b) the whole db.
**ii. When**
We could do 
(b.ii.a) when the user uploads/updates something in the enclave through TermHub, 
(b.ii.b) whenever a user actually uses TermHub in any way.

**Comment by Sigfried** [comment]
I think this is covered in other issues. Closing. @joeflack4, re-open if you think appropriate.

**Comment by joeflack4** [comment]
Oh yes, this is both (i) defunct, and (ii) we do have an action for it set up as well should we need it.
