### ISSUE TITLE
Bugfix: Create new concept set version inherits parents' concepts

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#208]
## Overview
Amin recently made a change so that when we want to delete a draft, we don't need to delete the expression items.

However, when we are creating a new version, that new version inherits _all_ concepts from the previous version. We want to delete any concepts that are inherited that are not part of what we're trying to add for the new concept set version.

## Context and prerequisites
Context: [Slack convo w/ Amin](https://cd2h.slack.com/archives/C034EG5ESU9/p1674056393105309?thread_ts=1673611109.643989&cid=C034EG5ESU9
Slack)
Prereqs: Amin to "we could add a parameter to the draft creation call to opt out of prepopulating"

## Sub tasks
- [x] Stay in communication w/ Amin to complete new param
- [x] Implement new param
- [x] Once param implemented, I no longer need (i) explicit deletes of concepts, (ii) wait/sleep in the code between these requests

## Details
Follows #204. In order to get all existing concept expressions in a new version to be deleted before adding the concepts the new version should have, we've had to add sleep intervals into the series of API calls. It's not clear exactly where the sleep needs to be and for how long, and how much the length of the sleep would change based on the size of the existing and new versions.

The call to get the existing expression ids (`.../objects/OMOPConceptSet/1000095509/links/omopConceptSetVersionItem`) seems to work fine, but then the deletion doesn't always delete all of them. Is it maybe that they haven't all actually been placed in the version yet (despite the fact that they appear in the links API call), and expressions keep getting added after we've executed the delete? Or is the problem in the next step: we've started the delete, but before it finishes, we start adding the new expression items and it interrupts the deletion?

The following curl commands won't entirely work, but illustrate what the python is doing. Reaching out to Palantir (Amin) for help understanding the problem. 

    source ./env/.env

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/create-new-draft-omop-concept-set-version/apply \
    --data '{"parameters": {"conceptSet": "[DM]Type2 Diabetes Mellitus", "intention": "", "current-max-version": 5.0, "baseVersion": 794639872, "intended-research-project": "RP-4A9E27", "versionId": 1000095509, "on-behalf-of": "51ffdc0e-e7e1-440e-bdab-9fbfe552dd1b", "sourceApplication": "TermHub", "sourceApplicationVersion": "0.0.1"}}' | jq
    sleep 10

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/objects/OMOPConceptSet/1000095509/links/omopConceptSetVersionItem

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/delete-omop-concept-set-version-item/validate \
    --data '{"parameters": {"concept-set-version-item": ["be130575-e61e-444d-8521-d245602c135b", "18a190d5-6db6-42ac-a696-6ba17fab145c", ...] }}' | jq

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/delete-omop-concept-set-version-item/apply \
    --data '{"parameters": {"concept-set-version-item": ["be130575-e61e-444d-8521-d245602c135b", "18a190d5-6db6-42ac-a696-6ba17fab145c", ...] }}' | jq
    sleep 10

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/add-selected-concepts-as-omop-version-expressions/apply \
    --data '{"parameters": {"concepts": [4034962, 4129519, 4129524, 4129525, 43531010], "includeMapped": false, "includeDescendants": false, "version": 1000095509, "isExcluded": false, "optional-annotation": "", "sourceApplication": "TermHub"}}' | jq

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/add-selected-concepts-as-omop-version-expressions/apply \
    --data '{"parameters": {"concepts": [45766050, 4016047, 4162239, 36674752, 4252356, 4270049, 4044391, 43022019, ...] , "includeMapped": false, "includeDescendants": false, "version": 1000095509, "isExcluded": true, "optional-annotation": "", "sourceApplication": "TermHub"}}' | jq

    curl  -H "authorization: $PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN"\
    -H "Content-type: application/json" \
                https://unite.nih.gov/api/v1/ontologies/ri.ontology.main.ontology.00000000-0000-0000-0000-000000000000/actions/finalize-draft-omop-concept-set-version/apply \
    --data '{"parameters": {"new-parameter": "hello new-parameter", "new-parameter1": "hello new-parameter1", "concept-set-containe": "[DM]Type2 Diabetes Mellitus", "version": 1000095509}}' | jq

**Comment by joeflack4** [comment]
Addressed by: https://github.com/jhu-bids/TermHub/pull/244
