### ISSUE TITLE
Live update of descendants, mapped, excluded while editing

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#217]
## Sub-tasks
- [ ] 1. UI updates
- [ ] 2. Algorithmic updates

### 1. UI updates
Should start from expression items, and show included, mapped, excluded from there. For each set of concepts related to an expression item:
- Sort by: 1) no flags, 2) `includeDescendants`, 3) `includeMapped`, 3a) include Descendants of Mapped (both flags), 4) `isExcluded`: show in red or something, same order as includes, also mark any included concepts above as excluded.
- Grouping: Visually group the concepts together, e.g. by (a) different background colors for groups of rows, like a set of rows with white background, then a set with light grey background, repeating ([example](https://support.content.office.net/en-us/media/d156448c-f88a-46f0-8578-415ac09dee46.png)), or (b) different line styles/colors on the left border of the table, like a thick line for one group, thin line for the next, repeating.

**Comment by joeflack4** [comment]
I prefer dark grey over dark red for excluded. Or maybe this kinda red/pink like from [bootstrap](https://getbootstrap.com/docs/4.0/components/alerts/):
![Uploading Screen Shot 2023-01-20 at 2.08.19 PM.png…]()

**Comment by joeflack4** [comment]
Closing in favor of:
- #938 
- #939
