### ISSUE TITLE
Reconnect db connection -- or, really, start using connection pooling

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#218]
When the postgres connection is lost, the backend doesn't reconnect. This kind of app should be using a connection pool.

### How to test
Run query on backend: capture `CON` variable for our global connection, close it, and run a new query and it should fail. And then I set up the connection pooling so that it initializes a new connection on request.

**Comment by joeflack4** [comment]
@Sigfried Is this now a duplicate of #479?

**Comment by Sigfried** [comment]
closing this and merging with #479
