### ISSUE TITLE
Add concept metadata

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#231]
## Overview
When we fetch information about concepts, we should also get metadata (e.g. whether or not a concept is standard). And that should be visible in the UI.

## Additional information
Joe's personal notes copy/paste
useful feature: adding a concept and different kinds of includingDescendants *

- * add this as an issue? get a better idea of this from siggie if so?
- Bryan
  - Bryan: The idea. if trying to put together concept set for rare disease and start from scratch. go to athena, search for name, search for synonyms, try to find a standard concept ID from athena and start from there. see what that maps to that is standard/nonstandard. descendants, subsumed by concept. that'd be starting point
  - different kinds of includingDescendants
    - would want the concept set to include all those (i) (standard) descendants, and (ii) the nonstandard ones as well. 
  - how to distinguish standard and non standard? in Athena. and also in concept table. there is the `standard` column in the `concept` table and I think standard is 'S'
- Siggie
  - What this requires is, when we get concepts back from the endpoint, we get concept metadata, and we could add this to our concept_counts table

**Comment by Sigfried** [comment]
Metadata added to tables in 8808ca0

**Comment by hugwuoke** [comment]
@Sigfried it looks like your comment on Feb 2 solved the problem!
