### ISSUE TITLE
Bug: Duplicate rows in `all_csets`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#242]
## Overview
This also appears if we check the `all_csets` table in the database.
<img width="836" alt="Screen Shot 2023-02-08 at 11 26 18 AM" src="https://user-images.githubusercontent.com/13045020/217590449-5ec7a234-463b-4486-9f79-b3dbaa3afa6c.png">

**Comment by hugwuoke** [comment]
Hopefully this is fixed :)
