### ISSUE TITLE
Error messages: Return & display to users

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#245]
## Overview
- what
  - Need to log this stuff too
  - Always return even Python errors to the user. Have good error message in front end when back end is broken
  - expose termhub/enclavewrangler errs to users specifically too
- how
  - likely (a) `fastapi.Response` subclass, or (b) a generic wrapper around fast api route. It will simply except these errors, log in backend, and return to user.

**Comment by hugwuoke** [comment]
@joeflack4 hmm looks like the pull request that was supposed to close this issue didn't, so I'm closing it now.

**Comment by joeflack4** [comment]
Thanks! It may be that I was handing this off to Siggie but I don't see them assigned on it. There may be some more work we can do on the frontend to display more detailed error messages but we can always re-open / change this if needed.
