### ISSUE TITLE
Enclave Request: Objects API: Show updates/deletes

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#261]
## Overview
Right now if we query the objects API, we can get a list of new things created after a certain date, but not updates/deletes.

Mirror enclave ticket:
https://unite.nih.gov/workspace/issues-app/issue/ri.issues.main.issue.290e7a49-fdb4-493d-853b-3ae24d5b1bde

**Comment by hugwuoke** [comment]
@joeflack4 Is this still an issue?

**Comment by joeflack4** [comment]
Oh this one is done! Thanks.
