### ISSUE TITLE
Docs: UI: icons/colors

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#264]
## Sub-tasks
- [ ] 1. Add documentation, either the main `README.md` or `frontend/README.md`
- [x] 2. Add meaning indications in UI
a. a 'key'
b. onHover tooltips

## Related
These issues talk about UI for color/icons:
- #82 
- #217

**Comment by Sigfried** [comment]
From [Mar 1 meeting notes](https://docs.google.com/document/d/1tqePEAeZO899eJ6JmuXSAy0SSpaNP9DFD1IgsNEljSc/edit#heading=h.qxdo9v2tgirg):

![Image](https://user-images.githubusercontent.com/1586931/222465314-08909e81-015d-4e8f-a28d-ba5bc2efb57c.png)

**Comment by joeflack4** [comment]
@Sigfried Is this issue done?

**Comment by joeflack4** [comment]
Deciding not needed in the docs right now.
