### ISSUE TITLE
Docs: Conditional 'about' text to main page

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#270]
## Overview
When the user first goes to TermHub, they shouldn't just see blank space and the 'select cset' box, but there should be at least a paragraph of text saying to guide the user.

## Sub-tasks
- [x] 1. Come up w/ some text
- [x] 2. About / Help
- [x] 3. Main page (cset search)

### 1. Come up w/ some text
Lisa created something here: https://docs.google.com/document/d/1DfI17wh9OQx5hWxjtNg3Wkd8sZVi64Ict9_eK5Q0gm0/edit

### 2. About / Help
Improve / add to the normal 'About / Help' page to have this text

### 3. Main page (cset search)
Have this same / similar text appear conditionally. If the user goes to the page and has nothing selected, have it appear. When the user selects a cset, have it disappear.

**Comment by Sigfried** [comment]
@Leskena2 -- Does it seem good now? https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets

**Comment by Leskena2** [comment]
Yep but remove the parenthetical “(should we mention the metadata?)” – under the CSET COMPARISON line.

From: Sigfried Gold ***@***.***>
Date: Thursday, March 2, 2023 at 9:34 AM
To: jhu-bids/TermHub ***@***.***>
Cc: Lisa Eskenazi ***@***.***>, Mention ***@***.***>
Subject: Re: [jhu-bids/TermHub] Docs: Conditional 'about' text to main page (Issue #270)

      External Email - Use Caution





@Leskena2<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeskena2&data=05%7C01%7Cleskena2%40jh.edu%7Ce9d72ca7d0514ccf1fd008db1b2b44c2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638133644881126233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wekHyP9k14UOe6qP84cbmm5YjzwspVgTE%2BAN%2FkFSlYE%3D&reserved=0> -- Does it seem good now? https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ficy-ground-0416a040f.2.azurestaticapps.net%2FOMOPConceptSets&data=05%7C01%7Cleskena2%40jh.edu%7Ce9d72ca7d0514ccf1fd008db1b2b44c2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638133644881126233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2aVX%2FnDHjNXYFi8AzMA008DciySz%2Fn8kzG32JmzxHNc%3D&reserved=0>

**Comment by joeflack4** [comment]
@Sigfried Stylistically my only inclination is to center it a bit more. E.g. if talking about this in pixels, maybe like 30-50px margin at the top of the block of text, and maybe 100px+ on the left and right.

**Comment by hugwuoke** [comment]
@Sigfried Looking on TermHub this looks done!
