### ISSUE TITLE
User testing feedback

### ISSUE THREAD

**Issue by Bluestars1** [jhu-bids/TermHub#275]
### Overview
Summary of what the bug / or poor UX (user experience) is. poor UX experience on comparison sheet

### To Reproduce
1. follow steps 

### What browser are you using?
e.g. Chrome.

### Screenshots _(optional section)_
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/36236025/223836438-ca9df380-aad4-42d2-b3c2-8cd7f08eb1b1.png">

**Comment by joeflack4** [comment]
Hey @Bluestars1 . Much thanks on opening this!

This screenshot helps, but I don't see any additional details about what's going on here. My guess is that you proceeded to enter the enclave and do `E_01` through `E_07`, but you failed to get through the steps, possibly because (a) we may have missed adding a required step to the checklist? Or (b) perhaps we mis-described on of the steps? Or (c) perhaps because of an enclave issue? Can you fill us in a bit more on where this testing failed?

**Comment by Bluestars1** [comment]
Hi Joe I will have to take another look and get back to you Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joeflack4** [comment]
Oh, I think I see your pass/fail info here: https://docs.google.com/spreadsheets/d/1aMsGwV6JkWSMpaEwF4d7ne7aBLr2p-s_dRBWgjeHG3U/edit#gid=880790843

Maybe this is all the information we need right now.

**Comment by Bluestars1** [comment]
Yes - Great!!! Let me know if you need my help.

Thank you,

Eileen Keck
Sr Programmer Analyst - Innovation Services
Stony Brook Medicine Information Technology (SBMIT)
7 Flowerfield, Suites 44 & 88
St. James, NY 11780-6060
Phone: (631) 444-4021 Fax: (631) 444-4075
***@***.******@***.***>


[emailsig]
Follow Stony Brook Medicine on Facebook<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2Fstonybrookmedicine&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087220957&sdata=JPcoyuWkBQEyGUdQMLztYpQ%2FdpvwDuHAoQNNPrOIyWw%3D&reserved=0> • Twitter<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2Fstonybrookmed&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087220957&sdata=oxPjTnHOITNtFdisEg9v8rkdd0egdvz1D9kZ4a4Uyeo%3D&reserved=0> • YouTube<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FStonyBrookmedicine&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087230953&sdata=KRssIbRbGMbrmTDud7tQ4WFnuKZfq%2BWvWAGgocErCJ0%3D&reserved=0> • Instagram<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.instagram.com%2Fstonybrookmedicine&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087230953&sdata=gwy%2FHql2hvPSAf3%2BkvD36Ij1uIz6RwtjXXTOo%2BqwcFc%3D&reserved=0> • LinkedIn<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fstony-brook-medicine&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087240945&sdata=9BNSQ%2B0d7LTznXJ8IQXE%2FTwIHrl%2FLlgjPbrjnxvmsjs%3D&reserved=0>
Follow Stony Brook Children’s on Facebook<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2Fstonybrookchildrens&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087240945&sdata=JWeDzSIAMrQ%2Bex6153RTfkPtoGBNfeYIS2FtdRX71xE%3D&reserved=0> • Twitter<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2Fstonybrookkids&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087250937&sdata=7lK2CHtxoaA2O1KkgiyXXIVNxY8UbKOL1vPTfpPrIhk%3D&reserved=0> • YouTube<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FStonyBrookchildrens&data=02%7C01%7CEileen.Keck%40stonybrookmedicine.edu%7Ccb8ea6b294864c53271f08d7cb46feb7%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C637201378087250937&sdata=o2f6rOEJJknZmqWsGJnO4%2FFYhPwWYBVv4tpwrCYZK74%3D&reserved=0>



From: Joe Flack ***@***.***>
Reply-To: jhu-bids/TermHub ***@***.***>
Date: Wednesday, March 15, 2023 at 11:37 AM
To: jhu-bids/TermHub ***@***.***>
Cc: "Keck, Eileen" ***@***.***>, Mention ***@***.***>
Subject: Re: [jhu-bids/TermHub] Testing (Issue #275)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Oh, I think I see your pass/fail info here: https://docs.google.com/spreadsheets/d/1aMsGwV6JkWSMpaEwF4d7ne7aBLr2p-s_dRBWgjeHG3U/edit#gid=880790843<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1aMsGwV6JkWSMpaEwF4d7ne7aBLr2p-s_dRBWgjeHG3U%2Fedit%23gid%3D880790843&data=05%7C01%7Ceileen.keck%40stonybrookmedicine.edu%7C8960ae271d7b4742be1008db256b21d3%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C638144914312895904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SehXKLmgooreYPO2cCrlB7OJl%2BPmOv662%2F3O1FZBrvg%3D&reserved=0>

Maybe this is all the information we need right now.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhu-bids%2FTermHub%2Fissues%2F275%23issuecomment-1470265015&data=05%7C01%7Ceileen.keck%40stonybrookmedicine.edu%7C8960ae271d7b4742be1008db256b21d3%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C638144914312895904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a1XdDbOSnz3gDjsCQRnJQiC3bvu5rd2%2FytZ2vJDcBXM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIUOV6OUR5JVAAM5GENDCFTW4HO2DANCNFSM6AAAAAAVUGO6JA&data=05%7C01%7Ceileen.keck%40stonybrookmedicine.edu%7C8960ae271d7b4742be1008db256b21d3%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C638144914312895904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WKJsvO9SirGaXsSHWtTH8x7fmjPRD%2FXcKljVYQ2m%2BLY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by e-mail and destroy all copies of the original.

**Comment by hugwuoke** [comment]
@hugwuoke check to see if this can be combined with other user testing issues.
