### ISSUE TITLE
State management refactor

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#291]
## Summary
Finish refactor of state management from `searchParamsToObj` and `updateSearchParams` to `AppStateProvider` and `DerivedStateProvider` (all in `State.js`).

## Details
We want state to be saved to the url. Right now, `updateSearchParams` and `searchParamsToObj` are still used for cset editing state. There's an `editCsetReducer` used by `AppStateProvider`, but it's not being used.

I'm not sure what all `AppStateProvider` is being used for at the moment. Maybe it's too much refactoring work for too little benefit to be worth finishing, but the `updateSearchParams`/`searchParamsToObj` system feels really kludgy and I didn't want to make it more wonky as I implemented more stuff to track with state.

But the old way was working to save state to the url. I haven't set up the new way to do that.

Issue #290, tracking collapse/expand state for concept hierarchy wasn't being saved to url (it probably should be), it was using (parent) component state, which I wanted to clean up, but I haven't gotten `AppStateProvider` to handle it yet, so it's just broken.

**Comment by Sigfried** [comment]
maybe don't do this at all

**Comment by hugwuoke** [comment]
@Sigfried your comment on April 7th left me confused about whether or not to close this issue so I just to bring it to your attention.

**Comment by joeflack4** [comment]
FYI @Sigfried I didn't see any other issues about state, so I took the liberty of giving a more concise title and adding previous title as a summary description in the body.

**Comment by Sigfried** [comment]
See #461
