### ISSUE TITLE
Selecting concept sets is too slow

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#293]
Load is taking uncomfortably long. Could we split it into parts so user can start using selection immediately?

Might require doing more data assembly in javascript instead of backend. Yes, we can do this. Will be much more responsive for users.

But, also, should we allow multi-select on cset search select list?

**Comment by hugwuoke** [comment]
@Sigfried I haven't been experiencing this problem when I try to load concept sets, so I'm going to close.

**Comment by joeflack4** [comment]
It was going very slow recently!
I don't know what Siggie (and maybe Fabio, Amir, or Matthew) might have done to work on this, but @Sigfried personally I am curious to learn at some point how this was fixed.
