### ISSUE TITLE
Refactor data fetching from backend

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#295]
It's all intertwined right now and makes it very slow when changing which csets are selected and also don't have a good way to select different data for new pages or situations.

Want front end to download one cset at a time and not need backend to calculate the precision/recall/shared, requiring all to be selected at once. Or, it could calculate it, but not bundle it with everything else.

And concepts could be loaded in a circular cache on the front end maybe.

@Leskena2 and @hlehmann17: the medication cset comparison stuff would be a lot easier if we had this done already. And it would fix the bad slowness issues.

**Comment by Sigfried** [comment]
@amirmds, Assuming we're going to stick with https://tanstack.com/query/latest/ for data fetching, it might be worth looking at https://github.com/lukemorales/query-key-factory.

Also, in the stub class, since it's not a component and I can't use hooks, I'm switching from `useQuery` to `queryClient.fetchQuery` ([docs](https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientfetchquery)).

**Comment by joeflack4** [comment]
@Sigfried Unassigned Hope from this one for now. Just going over her project board. If you need her again on this, please feel free to add her and clarify tasks needing done.
