### ISSUE TITLE
OAK questions/issues

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#303]
### Overview
Holding place for questions and issues we're having with [OAK](https://github.com/INCATools/ontology-access-kit) that may require fixes/updates there.

## Issue list
- [ ] 1. Children speed
- [ ] 2. How to: get smallest subgraph?
- [ ] 3. How to: Add nodes and edges?
- [ ] 4. #312
- [ ] 5. #313

### 1. Children speed
Fetching a term's children is slow (0.5-2 seconds) 
> _Chris said_: Edge: it is possible to concretize the view and index it, which should make things much faster..

_Siggie_: @cmungall: How do we do that?

### 2. How to: get smallest subgraph
Given a set of curies (could be tens or hundreds), how do I get the smallest connected subgraph containing them all?
_Chris said_:
> Adding some docs on extracting subgraphs https://github.com/INCATools/ontology-access-kit/pull/550/files#diff-37820320575347f0b2c508013e1616d33c409a1113db364ae726aae11aaa086aR313-R328
> there are also methods to do a transitive reduction to get rid of intermediate nodes

### 3. How to: Add nodes and edges?
is there a way I can add nodes and edges to the graph without having to rerun the whole pipeline that created the semsql files?
_Chris said_:
> Yes, you can pass in kgcl commands to make changes

**Comment by cmungall** [comment]
I think 1 is resolved, provided you don't care about existentials and RBox axioms?

**Comment by Sigfried** [comment]
> existentials and RBox axioms

I don't know what those are yet.

**Comment by joeflack4** [comment]
I had to do some googling too. Base on my understanding:
Existential Restrictions: where / how something (e.g. class) can be used (domain (e.g. what classes can use it) & range (e.g. what values/relationships can it have) restrictions)
RBox: Information about what types of edges are sub/superclasses of one another (e.g. hasParent would be a subclass / narrower than hasAncestor).

@cmungall I would imagine we don't care enough about this. Awesome regarding the children query speed. Is that speed upgrade going to be in the next version of OAK to be pushed to PyPi soon?

**Comment by joeflack4** [comment]
@Sigfried Can you look at newly added sub-issue _4. Subgraph speed & bugged extra nodes_? Might be helpful to make a separate issue for this one. Let me know your thoughts. If this is not solvable on our own, we should ping Chris next week.

**Comment by joeflack4** [comment]
@cmungall Sounds good, I can do that. I imagine you want them here and not in `ontology-access-kit`, though for any genuine OAK issues I can open mirror issues there. I just opened up separate issues for (4) and (5) but I will do the same for these others next week.

**Comment by joeflack4** [comment]
Not using OAK currently, and not planned.
