### ISSUE TITLE
OAK: Subgraphs: multiple disconnected subgraphs

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#313]
## Expected behavior
a. 1 list edge, for the smallest possible subgraph only
b. List of lists, where each sub-list is a different subgraph _(e.g. `[[a -> b], [b -> c], [a -> d], [d -> c], ... [...]]`)_
c. Like 'b', but List of 1 nested dictionary for each subgraph _(e.g. `[{a: b: c ...}, {...}]`)_

## Actual behavior
32 edges in one list: [multiple-subgraphs.json.zip](https://github.com/jhu-bids/TermHub/files/11348821/multiple-subgraphs.json.zip) _(e.g. `[a -> b, b -> c, a -> d, d -> c]`)_

## Possible causes
It looks like it's returning every subgraph that links the two, but not the smallest subgraph, which makes sense. I think this is the default behavior. Perhaps it is the only behavior for `subgraph_from_traversal()`?

### a. Return only smallest possible subgraph?
Perhaps there is an argument to pass to `subgraph_from_traversal()` that will allow us only to get the smallest subgraph ("minimal subsumption tree")? If not, is this some functionality we could add to / request be added to OAK?

### b. Return each subgraph in a separate list
I think it would also be better if TermHub, or ideally OAK, returned each subgraph separately. There should at least be 1 subgraph which is the direct edge between the two nodes (see CSV snippet above). But when I was looking at the JSON, I noticed there was another subgraph that was about 4 edges long. That leaves another 25~ or so edges. So rather than this returning a list of edges, it should return something like a list of lists of edges.

## Additional information
On 2023/04/27 I tried to get the subgraph between these two nodes which have a direct relationship:

```csv
concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
4043671,24969,Subsumes,2011-07-31,2099-12-31,
```

I hit our new subgraph route w/ the following query: http://127.0.0.1:8000/subgraph/?cid=24969&cid=4043671
Which uses basically the following code:

```py
def subgraph(cid: List[str]):
    seeds = ['N3C:' + _id for _id in cid]
    traversal = oi_pkg.TraversalConfiguration(up_distance=oi_pkg.Distance.TRANSITIVE, down_distance=oi_pkg.Distance.DIRECT)
    return OI.subgraph_from_traversal(seeds, predicates=[IS_A, PART_OF], traversal=traversal).edges
```

Slack discussion: https://obo-communitygroup.slack.com/archives/C03D93DEALA/p1683312624254219

**Comment by cmungall** [comment]
does SNOMED have part-of edges? I thought it used SEP?

**Comment by joeflack4** [comment]
@cmungall @Sigfried Good point, I'd imagine you are probably right. I did try it without `PART_OF` and I got the same number of edges / same [performance](https://github.com/jhu-bids/TermHub/issues/312).

**Comment by cmungall** [comment]
That should only affect performance but it shouldn't change the output

This may be what you want:

https://incatools.github.io/ontology-access-kit/packages/interfaces/subsetting.html#oaklib.interfaces.subsetter_interface.SubsetterInterface.gap_fill_relationships

**Comment by Sigfried** [comment]
> does SNOMED have part-of edges? I thought it used SEP?

@cmungall, so far we're only using subsumes edges.

**Comment by Sigfried** [comment]
Oh, and, BTW, when I said in slack I got 208 disconnected subgraphs, that was wrong. I'm using d3-dag, and I got 208 root nodes, but only 12 disconnected subgraphs.

**Comment by Sigfried** [comment]
I got confused thinking I needed to import subsetter_interface but Harshad [explained on Slack](https://obo-communitygroup.slack.com/archives/C03D93DEALA/p1683316132406489?thread_ts=1683312624.254219&cid=C03D93DEALA) that I can reach gap_fill_relationships straight from my OI (SqlImplementation) object.

Seems to be working now. Only cursorily tested so far, but closing for now.

**Comment by joeflack4** [comment]
@cmungall @hrshdhgd We tried `gap_fill_relationships()` but it yielded no results.
```py
# Trying to get 1 or more subgraphs connecting 2 seed nodes

# Attempt 1: fail~. We get a list of edges for multiple subgraphs. It would be better to get a list of lists, where each sub-list is a different subgraph, 
traversal = oi_pkg.TraversalConfiguration(up_distance=oi_pkg.Distance.TRANSITIVE, down_distance=oi_pkg.Distance.DIRECT)
edges = OI.subgraph_from_traversal(seeds, predicates=[IS_A, PART_OF], traversal=traversal).edges

# Attempt 2: fail; got nothing
edges = OI.gap_fill_relationships(seed_curies=seeds, predicates=[IS_A])
edges = [x for x in edges]  # []
```

**Comment by joeflack4** [comment]
Not using OAK currently, and not planned.
