### ISSUE TITLE
Comnparison table showing empty when it shouldn't

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#315]
Can't replicate now, but http://localhost:3000/cset-comparison?codeset_ids=869338732 was giving me an empty data even though all the data was loaded. After I set a javascript console breakpoint and reloaded a couple times, the data showed up. No idea what was going on or if this will occur again.

**Comment by hugwuoke** [comment]
@Sigfried if this hasn't come up since I think it is safe to close. I'm not sure if that is the case so feel free to reopen.
