### ISSUE TITLE
Loading the wrong concept set

### ISSUE THREAD

**Issue by hlehmann17** [jhu-bids/TermHub#321]
### Overview
I selected one concept set (N3C Montelukast (v3)), Loaded it, but when I viewed CSET Comparison, I got an asthma-related concept set.

### To Reproduce
1. Go to Home Page
2. Type 'Montelukast' in to search box
3. Select 'N3C Montelukast (v3)'
4. After 'Loading...', click on CSet Comparison
6. See error

### What browser are you using?
macOS Chome

### Expected behavior _(optional section)_
The Montelukast concept set

### Actual behavior _(optional section)_
We should see the Montelukast concept set

### Screenshots _(optional section)_
<img width="2000" alt="image" src="https://github.com/jhu-bids/TermHub/assets/16959014/9e6a0d4a-de9b-4900-bcf5-bc14b4829066">

**Comment by joeflack4** [comment]
That is quite unexpected! We'll look into that shortly.

**Comment by hlehmann17** [comment]
I found that this bug occurs when you select "compare csets" having selected only a single concept set. But with 2 or more, no bug.

**Comment by joeflack4** [comment]
@Sigfried I wonder if this one would be good for the students to tackle in a couple weeks.

**Comment by hugwuoke** [comment]
This actually still happens when you select compare csets with a single concept set.

**Comment by Sigfried** [comment]
I'm not seeing this now on either [prod](https://purple-plant-0f4023d0f.2.azurestaticapps.net/cset-comparison?codeset_ids=98165645) or [dev](https://icy-ground-0416a040f.2.azurestaticapps.net/cset-comparison?codeset_ids=98165645). @hlehmann17 -- If you want to recheck, that would be great. If you see the problem, could you re-open this issue and let me know? Thanks!
