### ISSUE TITLE
CSET Comparison page must retrieve concept data from DataAccessor

### ISSUE THREAD

**Issue by mtj0712** [jhu-bids/TermHub#338]
Also start getting other data from DataAccessor rather than from cr-hierarchy.

## Sub-tasks
- [x] getRowData() from frontend/src/pages/CsetComparisonPage.js retrieves concept data from DataAccessor rather than from cset_data
- [x] CsetComparisonPage() from frontend/src/pages/CsetComparisonPage.js retrieves concept data from DataAccessor rather than from cset_data

**Comment by hugwuoke** [comment]
@Sigfried closing because boxes are checked.
