### ISSUE TITLE
Adding installation of Git LFS to the set up instructions. 

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#342]
It would be awesome if you could work with Katherine on this because she is having a hard time installing pickle. 
-Siggie

**Comment by joeflack4** [comment]
Thanks for bringing to my attention. Will do this and will follow up with Katherine!

**Comment by joeflack4** [comment]
Addressed by: https://github.com/jhu-bids/TermHub/commit/e4c191b22e3bc3049e129e854fd15ebeb5707394
Will follow up with Katherine.
