### ISSUE TITLE
Delete extra copy of `networkx` pickled graphs

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#344]
## Overview
Hey @Sigfried. I just corrected a bug in the path where the pickle files were being saved to, as well as some other minor changes in [this commit](https://github.com/jhu-bids/TermHub/commit/b566bba1f7660f0db353e7e388e021a33daa630d).

I noticed that there are copies of these files at both of the following locations. I think the ones in `termhub-csets/networkx/` can be deleted. 
- https://github.com/jhu-bids/termhub-vocab/tree/b0cc420e42558c42ccf537578196ca79908622bf
- https://github.com/jhu-bids/termhub-csets/tree/6617c56126b127fea5f9ecf5696fd8b24b342220/networkx

**Comment by Sigfried** [comment]
@joeflack4  I'm not sure how to delete those. Can you? And close this?

**Comment by joeflack4** [comment]
@Sigfried I'm sure you know how to delete them! Either way, [done](https://github.com/jhu-bids/TermHub/commit/065f30b9e8f51802a22fa2c6b3a49cc5cd2fec3e)!
