### ISSUE TITLE
Grouping Issue: Hierarchy

### ISSUE THREAD

**Issue by forbeskat** [jhu-bids/TermHub#346]
Also see #154

- Ordering
     - Items don't always show up under their parents
     - Prefer to have parents sorted in order of number of their descendants with greatest first
     - If ordering is done at backend, FastAPI reorders dictionaries in alphabetical order by key, which messes it up; so started trying to do ordering in javascript, but not there yet.
- Filling in gaps
     - If multiple roots or disconnected subgraphs, find shared ancestors to connect them
     - [x] #347
     - Do we fill gaps on the server or at the client?
       - Using technique of transforming entire concept graph to undirected and then finding shortest paths, then converting back to directed:
         - probably not feasible on frontend, will slow people's browser's down too much and take too long to load huge graph.

There are several methods of constructing the hierarchy and we should choose one of them
- Backend
      - [OAK](https://incatools.github.io/ontology-access-kit/)
      - [NetworkX](https://networkx.org/documentation/stable/index.html)
      - [Neo4J](https://neo4j.com/)
- Frontend
      - D3-Dag
      - Graphology

Issues:
- Should we download as hierarchy (dictionary with concept_id key, children array value), or as edge list?
  - [ ] #348

Old Issues:
- [x] #316
- [x] #347 
- [ ] #217 
- [ ] #234 
- [ ] #235 
- [x] #290 
- [ ] #123

**Comment by joeflack4** [comment]
@Sigfried I've been meaning to bring this up at meetings but I'll throw it out here. I've been thinking of a simple REST API wrapper around OAK that we deploy as a separate server to sit in between TIMS and TermHub to serve both their purposes. We can later reimplement the TIMS side of things using Neo4J, Java, etc if we want.

**Comment by Sigfried** [comment]
Moved to #154
