### ISSUE TITLE
`Uncaught Error: error getting codeset_id during col header click`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#350]
## Overview
I was just trying to edit a cset in the comparison page, but I got this error and it failed to open up any editor UI.

```
EditCset.js:31 Uncaught Error: error getting codeset_id during col header click
    at EditCset.js:31:13
    at floating-ui.react-dom-interactions.esm.js:275:87
    at Array.forEach (<anonymous>)
```

<img width="1017" alt="Screen Shot 2023-05-30 at 2 51 42 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/01b8c934-6ddd-451e-b036-fb0750e97bc7">

**Comment by hugwuoke** [comment]
Probably been fixed
