### ISSUE TITLE
pgAdmin

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#359]
## Overview
[pgAdmin](https://www.pgadmin.org/download/) is a GUI for interacting with PostgreSQL databases. It will be useful for (i) looking around to familiarize yourself with the database tables, which may come in handy later, and (ii) troubleshooting: sometimes it can be handy to look at the raw source of the data in cases where you're not seeing any data somewhere (e.g on the frontend), or what you're seeing isn't what you're expecting.

## Sub-tasks
- [ ] 1. [Download pgAdmin 4](https://www.pgadmin.org/download/)
- [ ] 2. Add/Connect to TermHub server

### 2. Add/Connect to TermHub server
This page should help: https://www.pgadmin.org/docs/pgadmin4/development/server_dialog.html

If I remember correctly, when you open up pgAdmin, there's a "Servers" option at the top left. If you right click that, you can click something like "add server" which will open this dialog. In the "General" tab, you can add "TermHub" as the name. In the "Connection" tab, you can fill it out using the `TERMHUB_DB_*` variables in `env/.env`.

**Comment by mtj0712** [comment]
I finished connecting!

**Comment by hugwuoke** [comment]
I connected as well

**Comment by joeflack4** [comment]
Thanks guys!
