### ISSUE TITLE
Cache: Clear in frontend on version up

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#374]
## Overview
I looked around for an existing issue but didn't find one. I did a search and found this:

From: https://dev.to/flexdinesh/cache-busting-a-react-app-22lk
> **Cache Busting a React App**
> _A simple approach to cache busting in a React application_
> TL;DR - [SemVer](https://docs.npmjs.com/about-semantic-versioning) your app and generate a meta.json file on each build that won't be cached by the browser. Invalidate cache and hard reload the app when there's a version mismatch.

More info
- https://github.com/flexdinesh/cache-busting-example
- https://stackoverflow.com/questions/57993791/how-to-clean-the-browser-cache-each-time-a-new-version-of-the-web-application-i

**Comment by hugwuoke** [comment]
Is this more complex than the button that says close cache on the Help/About page. Probably it is lol

**Comment by joeflack4** [comment]
Yep. This is to automatically clear the cache on the frontend whenever it detects a new version. 

@Sigfried, I think you've already completed this? If so, can you close?

I know that another change we need to make is that in addition to source code version changes, database changes are another area where we have to clear the cache. For that, there's this issue #396

**Comment by joeflack4** [comment]
This is now redundant with #495
