### ISSUE TITLE
Print out hierarchy

### ISSUE THREAD

**Issue by hlehmann17** [jhu-bids/TermHub#377]
## Overview
To help SMEs in particular, we need to "print" out a hierarchy displayed on TermHub

### Is your feature request related to a problem? Please describe.
"Printing" a screen or scraping loses the hierarchical structure, making the print-out no better than exporting the csv from the Enclave Concept Set Browser

### Describe the solution you'd like
A button (?) that, when pressed, exports the current screen to a csv, with the hierarchy maintained

### Describe alternatives you've considered
"Print" from the browse file menu, selected everything on the screen, copying, and pasting

**Comment by joeflack4** [comment]
@hlehmann17 This sounds like a pretty cool feature!
@Sigfried What do you think about having @hugwuoke take a stab at this one? At least for the Python part of it?

**Comment by hugwuoke** [comment]
@Sigfried seems to be the same problem as described in #390 so closing this one.

**Comment by joeflack4** [comment]
@hugwuoke I think you're right! It looks like this issue is more detailed though, so I'm going to copy/paste this information over into the other issue.
