### ISSUE TITLE
Cset Comparision page: Allowing users to include and exclude concepts when viewing results

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#381]
## Overview
We have given users the ability to choose whether or not to include Rx norm extensions. It would be good to extend this so users have more freedom to hide concepts that are not relevant to them such as NDC concepts. When Rx norm extension concepts are hidden it shows how many concepts were hidden the same feature would be good to extend to other categories users might want to hide.

**Comment by Sigfried** [comment]
Replaced by #547
