### ISSUE TITLE
Info panel: csets related to edited

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#382]
## Overview
Provide new info panel with related cset table from cset search page but use the selected csets instead of related so we can see precision/recall numbers in relationship to the cset being edited.

**Comment by Sigfried** [comment]
Hey @Matthew. The refactor has gotten us to the place that this is now possible. It should be pretty easy to implement now based on the work you already did. I can  help.

**Comment by Sigfried** [comment]
All the pieces are in place for this to work, except that more optimization is needed (see #508), which might break any implementation made now.

**Comment by joeflack4** [comment]
Since this is done, even if the new issue breaks this, it should merit a new issue. Closing
