### ISSUE TITLE
CSV upload familiarity

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#388]
## Overview
@hugwuoke I'd like your help with #265. I think I'll need to break this down into something smaller, though. And I think we may need some changes to the schema / fields of the CSV first, which I'll have to think about. For now, if you could do the following, it will be a good start! Can you tick these checkboxes and close the issue and respond here when done?

- [x] 1. Read #265 (including comments section) and get a general idea of what we're trying to do
- [x] 2. Read through the [upload CSV schema docs](https://github.com/jhu-bids/TermHub/blob/develop/enclave_wrangler/README.md#csv-schema)

**Comment by hugwuoke** [comment]
Read through it :)
