### ISSUE TITLE
Counts havent been getting updated. Bug Palantir

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#394]
## Overview
These are getting calculated regularly (most recent: June 8), but the latest counts are not being put where TermHub can reach them and the latest are from December 16. Kate said she would contact Amin and Saad about getting a weekly schedule for the counts to be put in the download area. We need to follow up.

https://unite.nih.gov/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.e393f03a-00d0-4071-802c-ff20e543ce01/master

https://unite.nih.gov/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.ca8c0730-d4d8-4dfa-85a7-35138982eb53/master

## Update 2023/09/18
Depends on vocab/counts refresh fix.

**Comment by joeflack4** [comment]
Added to:
- #203

**Comment by Sigfried** [comment]
I think this is fixed. @hugwuoke, can you confirm and close?
