### ISSUE TITLE
Clear cache: When DB updates

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#396]
## Overview
When the `manage` var `last_refresh_success` updates.

Compare cache datetime to the datetime in that variable.

<details><summary>June 15 2023 notes</summary>
<p>

**When (i) normal refresh, (ii) new cset members** is when that variable updates, if there's new data.

The db refresh doesn't completely work right now because the cache doesn't get cleared, e.g. `localStorage.clear()`.

Particularly tricky: it's one thing to clear the cache after the normal refresh process has completed, but another thing if we need to kick off a separate action to fetch members from the enclave.

## Sub-tasks list
- [ ] 1. Implement
- [ ] 2. Test

### a. Clear based on DB variable change
If we were to base this on `last_refresh_success`, the problem is that this variable gets updated during the normal refresh, but not during the `fetch_failures_0_members` GH action.

How to implement: Every request would to include in its payload a DB var - one of the variables in #400, possibly `last_refreshed_DB` (though a new one, `last_time_db_changed` makes more sense). Then, that variable would be stored in the frontend state. On every page refresh the frontend should check if the timestamp has changed. If so, it would update the state w/ the new timestamp and clear the cache.

Would be helpful to clear out DB vars that aren't used anymore and maybe streamline their naming.

### b. Clear via push event (web socket / HTTP streaming)
When refresh completed, we would push an event notification to the frontend and it would appear without them needing to do a page refresh. This involves more coding / architecture, and is beyond my current knowledge. But this would be the better user experience.

### Situation at the time
The user has to wait until the refresh is complete, which they have no way of knowing unless (a) they observe the [action logs](https://github.com/jhu-bids/TermHub/actions/workflows/refresh_db.yml), or (b) [notifications](https://github.com/jhu-bids/TermHub/issues/397) are implemented. Then, they would click the "Empty the Data Cache" button in the ["Help / About" page](https://icy-ground-0416a040f.2.azurestaticapps.net/about).

### May / may not depend on
- #400

</p>
</details>

**Comment by joeflack4** [comment]
@Sigfried I believe you've already started on implementation "a" as described above.

**Comment by joeflack4** [comment]
@Sigfried Hope and I completed #400, so we can get started on "possible solution 'a'" now.

I'm going to be out until Tuesday. If you want, you can work with Hope and instruct her to include the timestamp from the `last_refresh_success` variable in the payload of some/all endpoints, and then you can use this information to know when cache is out of date.

**Comment by joeflack4** [comment]
@Sigfried Have you completed this (using option 'a')? Or does it still need more work? Anything more needed from me?

**Comment by Sigfried** [comment]
Yes, I used Option A. This needs to be tested -- quite urgently.

**Comment by Sigfried** [comment]
@hugwuoke -- can we talk about how to do this testing?

**Comment by joeflack4** [comment]
@Sigfried This is related to the new video on "[Websockets vs HTTP Streaming](https://www.youtube.com/watch?v=6RvlKYgRFYQ)"we were looking at.

I created a new grouping issue (#534) and added this issue and another one to it.

I also updated the title of this issue and added:
> Particularly tricky: it's one thing to clear the cache after the normal refresh process has completed, but another thing if we need to kick off a separate action to fetch members from the enclave.

**Comment by Sigfried** [comment]
Not relevant anymore
