### ISSUE TITLE
DB refresh: Broken due to read only

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#405]
## Overview
DB Refresh is [broken](read-only transaction) because of error:

```
sqlalchemy.exc.InternalError: (psycopg2.errors.ReadOnlySqlTransaction) cannot execute INSERT in a read-only transaction

[SQL: INSERT INTO concept_set_container ...
```

## Related
Can be fixed by fixing: 
- #404

**Comment by Sigfried** [comment]
Can you give me the actual SQL command that failed?

**Comment by Sigfried** [comment]
Looking into it. Might be a question for IT, but they don't support postgres. ... [google ERROR: cannot execute INSERT in a read-only transaction](https://www.google.com/search?q=ERROR%3A+cannot+execute+INSERT+in+a+read-only+transaction&rlz=1C5CHFA_enUS990US991&oq=ERROR%3A++cannot+execute+INSERT+in+a+read-only+transaction&aqs=chrome..69i57j69i58.555j0j7&sourceid=chrome&ie=UTF-8)

**Comment by Sigfried** [comment]
@joeflack4: Don't know what caused it to go into read only mode. Would be worth researching to figure that out. But the following shows the problem and how to fix it.

    termhubthadmin@termhub >  insert into public.counts values (null, 'test','test','test',0, 0);
    ERROR:  cannot execute INSERT in a read-only transaction

    termhubthadmin@termhub >  SHOW default_transaction_read_only;
    ┌───────────────────────────────┐
    │ default_transaction_read_only │
    ├───────────────────────────────┤
    │ on                            │
    └───────────────────────────────┘
    (1 row)

    termhubthadmin@termhub >  SHOW transaction_read_only;
    ┌───────────────────────┐
    │ transaction_read_only │
    ├───────────────────────┤
    │ on                    │
    └───────────────────────┘

    termhubthadmin@termhub >  SET default_transaction_read_only=off;
    SET

    termhubthadmin@termhub >  SHOW transaction_read_only;
    ┌───────────────────────┐
    │ transaction_read_only │
    ├───────────────────────┤
    │ off                   │
    └───────────────────────┘

    termhubthadmin@termhub >  SHOW default_transaction_read_only;
    ┌───────────────────────────────┐
    │ default_transaction_read_only │
    ├───────────────────────────────┤
    │ off                           │
    └───────────────────────────────┘
    (1 row)

    Time: 18.173 ms
    termhubthadmin@termhub >  insert into public.counts values (null, 'test','test','test',0, 0);
    INSERT 0 1

**Comment by joeflack4** [comment]
Excellent thank you!

What I do know is that I found out about this when I was uploading a backup schema and I had a message in my terminal saying out of memory. My computer wasn't out of memory, neither random access or disk. So I was thinking perhaps our database ran out of memory but yet you were just able to do an insert. Perhaps the database upload was trying to do a bigger insert. I might want to check to see what our maximum memory is on it and where we currently are at. Since this read only thing happened immediately afterwards I would have to imagine it is related somehow.

**Comment by joeflack4** [comment]
I'm not sure why, but it got set to `on` again. I turned it off again. I don't know if this is just a one/two-time thing or if this will be a recurring problem, or what's causing it.

I did a google search as to why this would happen, but couldn't find anything. 

If this keeps happening, I've proposed a solution in #404.

I'm gonna close this issue for now but will re-open if this re-occurs.
