### ISSUE TITLE
Improve CSET table(s) loading performance

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#411]
## Overview
Improve performance by making the table not loading all records at first (lazy loading). There are different ways to make it scrollable (e.g. pageable)

## Sub-tasks
- [ ] 1. CSET table(s) performance: Lazy loading
- [ ] 2. CSET table(s) performance: Load in chunks
  - #620

## Related
- #514

**Comment by joeflack4** [comment]
#514 is sort of a grouping issue in a way fro this.

**Comment by joeflack4** [comment]
@Sigfried Is this still an issue?
