### ISSUE TITLE
Improve the legend in Cset comparision

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#419]
- [x] Add new terms to make the legend better, split the legend so there is a part that allows shows and a second part that only shows when the legend is being edited. (Siggie had some ideas as to what this would entail in more detail).

- [ ] Once completed add to the testing script to open the legend and ask users to check if they understand the legend in both the editing and non editing versions of the legend.

**Comment by joeflack4** [comment]
@Sigfried I'm marking this completed. The manual testing part wasn't completed but IDK if we can / if it's worth getting people to check this; I think that push is done.
