### ISSUE TITLE
UX: "Empty the data cache": no feedback

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#426]
## Overview
I think it would be better UX if the user is able to see some kind of success message when clicking the "Empty the data cache" button on the "help/about" page. Currently there is not a console message either.

**Comment by mtj0712** [comment]
Solved in pull request #470.

**Comment by joeflack4** [comment]
@Sigfried Do you know if this is completed? I saw it was linked to #470, but that PR was closed without being merged, and this is no longer on the project board either.
