### ISSUE TITLE
Export Json error (local only)

### ISSUE THREAD

**Issue by mtj0712** [jhu-bids/TermHub#440]
### Overview
Some errors with exporting JSON.

### To Reproduce
1. Go to the landing page
2. Select some concept sets
3. Click on 'LOAD CONCEPT SETS'
4. Scroll down to the bottom
5. Click on 'Export JSON
6. See error
7. Go to 'CSET COMPARISON'
8. Make some edits
9. Click on 'SHOW INSTRUCTIONS TO SAVE CHANGES'
10. Click on 'Click to export JSON'
11. See error

### What browser are you using?
Firefox, Ubuntu

**Comment by joeflack4** [comment]
I wonder if this is the same as?:
- #415

**Comment by Sigfried** [comment]
I just went through the steps and it's working fine for me right now. https://termhub-dev.azurewebsites.net/cset-download?codeset_id=573795

**Comment by mtj0712** [comment]
> I wonder if this is the same as?:
> 
>     * [json download error #415](https://github.com/jhu-bids/TermHub/issues/415)
> 
> 
> If so, Hope has begun work on that and I'll be reviewing this PR tomrorow:
> 
>     * [PR: Solving json download error #415 #429](https://github.com/jhu-bids/TermHub/pull/429)

It seems like this is the same issue.

> I just went through the steps and it's working fine for me right now. https://termhub-dev.azurewebsites.net/cset-download?codeset_id=573795

It works for me too when I do this with termhub-dev.azurewebsites.net link, but it does not work locally. It might be just my local problem.

**Comment by joeflack4** [comment]
@mtj0712 Thanks for clarification! @Sigfried @hugwuoke I linked this to the PR #429 which I think you guys are reviewing / merging soon. So in the process of that, if there's time, see that this works locally to ensure that this issue is closed correctly.

**Comment by hugwuoke** [comment]
This should be fixed, if a pull doesn't fix it feel free to reopen.
