### ISSUE TITLE
DB refresh: overall strategy

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#444]
There are a [lot of db refresh issues](https://github.com/jhu-bids/TermHub/issues?q=is%3Aissue+is%3Aopen+refresh). We need to go through and organize. But I think we also should have a new strategy for handling db refresh, which we've started talking about, but there's more to say.

As per #442, we'll call `refresh.py:refresh_db()` directly (on clicking refresh button) instead of calling `routes/db.py:db_refresh_route()` which triggers the github action to dispatch `.github/workflows/refresh_db.yml` (which then just calls `refresh.py:refresh_db()`.)

There's a bunch of work in #395 and probably elsewhere about keeping track of refreshes, partly because they take a long time. Most of that time is spent dropping and recreating ddl tables. We've talked about being selective and only updating those tables for the newly added data (#448). I don't know if there's an issue for that. I can write the sql code, but what I need in order to write it is to know what's been newly added. I'd like a table with columns like (`table_added_to`, `key added`, `time_added`, `propagated_to_derived_tables=false`) -- and then switch propagated to true after doing that.

**Comment by joeflack4** [comment]
Talks about a number of issues that are either done or low priority now. closing.
