### ISSUE TITLE
DB refresh: bug:  relation "csmi_idx1" already exists

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#454]
## Overview
I'm running the DB refresh but getting an unexpected error.

## Sub-tasks
- [ ] 1. Fix the issue
- [ ] 2. Re-set the GitHub action cronjob from 1x/day back to 20 min

## Important tips for debugging
@Sigfried if you try to fix this:
1. Set a breakpoint: in `utils.py` in `refresh_termhub_core_cset_derived_tables()`, line 60 (`for module in ddl_modules:`).
2. Save 20 minutes: You can do it a lot faster (get to your breakpoint 20 minutes sooner) by adding this line `cset_versions = [cset_versions[0]]` above this line `for cset in cset_versions:` in `objects_api.py` (~line 357). I'll check your results, and if you do this, I'll make sure that I re-run it to fetch the rest of the things that would have been skipped by this (I need to fetch like a month+ worth of data anyway).

## Error
`ProgrammingError('(psycopg2.errors.DuplicateTable) relation "csmi_idx1" already exists\n')`

## Investigation
It looks like it's running these correctly:
```sql
DROP TABLE IF EXISTS n3c.cset_members_items_new CASCADE;

CREATE TABLE n3c.cset_members_items_new AS ...
```

So why is it erroring here? Shouldn't this index not exist if this is a newly created table?:
```sql
CREATE INDEX csmi_idx1 ON n3c.cset_members_items_new(codeset_id);
```

I checked the indexes on `cset_members_items` and I see what I would expect: 
[Query Results.csv](https://github.com/jhu-bids/TermHub/files/11901399/Query.Results.csv)

I checked for `cset_members_items_new` and got 0 results as expected too. So why the error?

**Comment by Sigfried** [comment]
Hey @joeflack4, you can't have two indexes with the same name in the same schema. It's a drag.

**Comment by joeflack4** [comment]
@Sigfried Ah thank you, I think I can find out a fix on my own now.
However I'm kinda shocked. I have no idea how the refresh was working before. I don't imagine it was just somehow not indexing.
