### ISSUE TITLE
Grouping issue: State management

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#461]
Finished a big round of state management/data download refactor a couple weeks ago. #291 can be closed. Refactoring further now.

- [ ] Incorporate DataAccessor into AppState
        - AppState is hook-based and can only be used in components; DataAccessor is not; but need to combine data from them sometimes.
        - Specifically, I want axiosCall to be able to add to Alerts state
        - Hmmm... Currently DataAccessor, which is all about caching, is closely tied to fetchItems, oneToOneFetchAndCache, and axiosCall; maybe all that should instead be tied to a data tracking slice in AppState

**Comment by joeflack4** [comment]
I'd love to learn about how this works some day if there's ever time for that.

**Comment by Sigfried** [comment]
@joeflack4 -- Happy to walk you through it anytime.
