### ISSUE TITLE
Prep for demo

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#475]
@hugwuoke 
Put demo script here

@mtj0712 
On develop branch tomorrow (Jul 11) morning, test Hope's script

@Sigfried @joeflack4 
Fix immediate bugs

@Sigfried 
Tell Hope: What's broken, etc, for purposes of demo script.

**Comment by mtj0712** [comment]
Local test:
- CSET COMPARISON:
-- Show instructions to save changes --> Click to export JSON -> Internal Server Error
-- click to open this concept set in the Enclave --> loading error

Test after deploying:
- CSET COMPARISON:
-- Show instructions to save changes --> Click to export JSON -> No errors
-- click to open this concept set in the Enclave --> loading error

Other than this, the website functioned well, both locally and on deployment.
