### ISSUE TITLE
"Add a new concept set" button not working

### ISSUE THREAD

**Issue by mtj0712** [jhu-bids/TermHub#478]
### Overview
The button for adding a new cset does not work.

### To Reproduce
1. Clear the local cache (enter 'localStorage.clear()' in the browser console)
2. Click on 'EXAMPLE COMPARISON'
3. Click on 'ADD A NEW CONCEPT SET'
4. Open the browser console
5. See error message (Firefox: 'searchParams is undefined', Chrome: 'Cannot read properties of undefined (reading 'keys')')

### What browser are you using?
Firefox, Chrome (Ubuntu)

### Expected behavior
'ADD A NEW CONCEPT SET' button disappears; a new, empty cset column appears at the right end of the table

### Actual behavior
'ADD A NEW CONCEPT SET' button disappears, but the cset comparison table does not change

**Comment by hugwuoke** [comment]
Add to a milestone refactor data caching with refactor lazy loading
