### ISSUE TITLE
DB refresh: updating documentation

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#485]
Ideally when the GitHub action refreshes the database, it should commit the changes to the counts_runs tables to the respective markdown files then merge the changes into develop ~ Joe

**Comment by joeflack4** [comment]
@hugwuoke Thanks very much for being proactive w/ this issue and the PR! I added this to [the grouping issue](https://github.com/jhu-bids/TermHub/issues/260).
