### ISSUE TITLE
Bug: Load concept sets: `P.unmount is not a function`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#488]
## Overview
Maybe the real issue here is that the "load concept sets" button is appearing when it should not. Look at the screenshot below. Isn't that what it means for them to be loaded? I effectively loaded them by opening via URL below. So should not the load concept sets button go away or be greyed out?

---

Stephanie was trying to use this on TermHub dev (#489): https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=417730759&codeset_ids=423850600&codeset_ids=966671711&codeset_ids=577774492 but experienced some issues.

This page loaded after 1-2 minutes.

<img width="1515" alt="Screen Shot 2023-07-19 at 4 39 00 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/b9e6f670-96d1-4b20-8068-0a1efed13046">

Then, when I clicked "load concept sets", I got the following error:
```
content.dd261dc5.js:1 Uncaught (in promise) TypeError: P.unmount is not a function
    at O (content.dd261dc5.js:1:320337)
    at K (content.dd261dc5.js:1:325123)
    at MutationObserver.observe.childList (content.dd261dc5.js:1:325905)
O @ content.dd261dc5.js:1
K @ content.dd261dc5.js:1
MutationObserver.observe.childList @ content.dd261dc5.js:1
```

## Additional information
I observed no errors in the backend logs.

**Comment by Sigfried** [comment]
I think this is fixed
