### ISSUE TITLE
Bug: Clear cache button broken?

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#492]
### Overview
@Sigfried I think you said at the meeting today that the button is broken and that we need to be manually doing `localStorage.clear()` in the JS console, and that there is a fix for this, but it just hasn't been deployed yet?

If so, I'm just creating this issue so that it stays on our radar.

Either that or I was just really tired and my mind was making stuff up.

**Comment by Sigfried** [comment]
@joeflack4, no, you weren't making it up. I think it's fixed now.
