### ISSUE TITLE
Bug: Sorting: new cset + post hierarchy

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#506]
## Overview
After sorting and restoring hierarchy view with new cset defined, it's screwy

## Sub-tasks
- [ ] See if this bug reappears after restoring unnested display option: #929 

## To Reproduce
1. Go to [state after copying Sulfonylureas v5 to new concept set](https://icy-ground-0416a040f.2.azurestaticapps.net/cset-comparison?codeset_ids=244768379&sstorage={%22newCset%22:{%22codeset_id%22:-1,%22concept_set_version_title%22:%22New%20Cset%20(Draft)%22,%22concept_set_name%22:%22New%20Cset%22,%22alias%22:%22New%20Cset%22,%22source_application%22:%22TermHub%22,%22source_application_version%22:%220.3.1%22,%22codeset_intention%22:%22From%20TermHub%22,%22limitations%22:%22From%20TermHub%22,%22update_message%22:%22TermHub%20testing%22,%22is_draft%22:true,%22researchers%22:[],%22counts%22:{%22Expression%20items%22:21},%22intersecting_concepts%22:0,%22precision%22:0,%22recall%22:0,%22definitions%22:{%221502855%22:%22D%22,%221502856%22:%22D%22,%221559684%22:%22D%22,%221559685%22:%22D%22,%221594973%22:%22D%22,%221594976%22:%22D%22,%2219001408%22:%22D%22,%2219006908%22:%22D%22,%2219077659%22:%22D%22,%2219077681%22:%22D%22,%2219077682%22:%22D%22,%2219125221%22:%22D%22,%2219125223%22:%22D%22,%2221600749%22:%22D%22,%2221600766%22:%22D%22,%2221600767%22:%22D%22,%2240046211%22:%22D%22,%2240165994%22:%22D%22,%2240165997%22:%22D%22,%2240166002%22:%22D%22,%2240166003%22:%22D%22}}}):
2. Click "350 DISTINCT CONCEPTS" button in upper left
3. Click "New Cset" column heading in upper right to sort. It will look like: <img width="1408" alt="image" src="https://github.com/jhu-bids/TermHub/assets/1586931/814fba97-47bc-4045-81b1-1fb8298c6776">
4. Click "722 IN HIERARCHY". Now it's all messed up: <img width="1409" alt="image" src="https://github.com/jhu-bids/TermHub/assets/1586931/aff01198-a647-4f3b-997c-8b9f39bd65a5">
5. Refresh page and it will look right again.

**Comment by joeflack4** [comment]
@Sigfried Is this still an issue?

**Comment by Sigfried** [comment]
Mostly fixed, but not entirely. Still have some bugs with hide though expanded/show though collapsed

**Comment by Sigfried** [comment]
See if this bug reappears after restoring unnested dsiplay option: #929

**Comment by Sigfried** [comment]
The only way I could figure out to get the original sort order back after going back to nested is by reloading the whole page. A bit clunky, but it works.

I did open an issue https://github.com/jbetancur/react-data-table-component/issues/1260 to see if react-data-table-component can provide a way to do this without a reload, but not super important.

**Comment by joeflack4** [comment]
RE:
> The only way I could figure out to get the original sort order back after going back to nested is by reloading the whole page. A bit clunky, but it works.

I suppose you could trigger a page reload automatically when the user clicks the button? You could have it prompt them that a reload is necessary after they click the button.

**Comment by Sigfried** [comment]
The reload is automatic. It's working decently.

**Comment by joeflack4** [comment]
Ohh ok. I thought it was manual gj
