### ISSUE TITLE
Graph DB: Requirement: Subgraph from concept IDs

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#509]
Given a set of conceptIDs, return a subgraph (as edgelist and/or other graph representations):
  1. if possible, a connected subgraph; otherwise
  2. an unconnected subgraph with as few components as possible.

This may require adding nodes that were not in the requested set of concept IDs:
  1. To make paths between nodes where needed to join unconnected components
    - Find common ancestors
    - Fill in gaps between any requested concepts that have ancestor/descendant relationships
      - Minimally, in order to fill in shortest paths
      -  Ideally, to fill in all paths

**Comment by joeflack4** [comment]
I think this is basically done / defunct, depending on how you look at it.
