### ISSUE TITLE
DB Refresh: Bug: Voc/Counts: GH action - not running

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#519]
## Overview
The voc/counts GitHub action isn't working because it gets shut down randomly during the download datasets phase. This happened 2 days in a row.

### 2. Split actions
This may also help. Can split into 2 actions.

### 1. Not enough disk space?
I'm thinking the problem might be that the datasets are too large / the action doesn't have enough disk space.

#### Solutions
i. Perhaps I can download, upload, and delete them one at a time.

## Errors
Example logs: [1](https://github.com/jhu-bids/TermHub/actions/runs/5875249665), [2](https://github.com/jhu-bids/TermHub/actions/runs/5864137442)
> `The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.`

## Additional info
Normal errors show an 'exit 1' ([log](https://github.com/jhu-bids/TermHub/actions/runs/5843912029)).

Related:
- #626

**Comment by Sigfried** [comment]
@joeflack4 What's up with this? I'm looking at a codeset (984059771) that has counts, as of a few days ago at least:
![Image](https://github.com/jhu-bids/TermHub/assets/1586931/aa378991-eff8-4b41-b4c4-1f013281cc5f)
But it's not in our database:
![Image](https://github.com/jhu-bids/TermHub/assets/1586931/c67f6ef9-98d6-41dc-9cb7-e7e3309b57c9)
 (@hugwuoke, we should add a test for this that will be very similar to the test you're working on now, once that one is working.)

**Comment by joeflack4** [comment]
The answer to this is that it was created on `2023-08-17T18:56:41.374Z`, but the action has been broken since then, so the count has not been imported.
