### ISSUE TITLE
Concept search & inclusion

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#551]
In lieu of graph db, for now. 

Allow user to search for and add concepts by concept_id or typeahead on concept_name

Was going to use web sockets so that backend can respond immediately to typing in the typeahead, but probably better to just cancel call as user changes typeahead contents (#553.) Might also be good to do HTTP streaming so typeahead can start displaying matches more quickly?

**Comment by joeflack4** [comment]
This issue is replaced by:
- #774 
- #782
