### ISSUE TITLE
Deploy fails: `code E401` "Incorrect or missing password"

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#570]
## Overview
Siggie went to deploy today, accidentally deploying from the `develop` branch. However, that gave us an early warning that this branch is currently undeployable.

## Errors
The frontend dev GH action failed. See: [log](https://github.com/jhu-bids/TermHub/actions/runs/6241494677/job/16943780124)
<details><summary>Critical part of log</summary>
<p>

```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in: /github/home/.npm/_logs/2023-09-19T22_18_20_089Z-debug-0.log
```

</p>
</details> 

## Possible causes
I think this has something to do with the addition of `"@termhub/sdk": "^0.1.0",` to `package.json`.

Here's the diff(s): [diffs.zip](https://github.com/jhu-bids/TermHub/files/12667366/Archive.zip)
This diff was made via `git diff usage-stats develop`.
The `usage-stats` branch consists of 1 small commit that was made after branching off of `deployment-2023-09-07`, which is a `git tag` for the last stable commit we deployed from.

## Possible solutions
Assuming `termhub/sdk` is the issue:
a. Remove the TermHub SDK work from `develop` and work on it on a PR until we figure out how to fix the deploy
b. Fix it now
@Sigfried I'm thinking (a). You know this work better than I. Do you have any better understanding of how this is causing our GH action to fail? If so, can you communicate that to the infrastructure team to see if they can help us?

**Comment by joeflack4** [comment]
Note per #568, I was able to successfully redeploy the last successful commit from Sept 7. And I even was able to add the "usage statistics" JS snippet on top of that and successfully redeploy (#569).

I then tested out to see if deploying from `develop` would fail again w/ the same message, and it did.

**Comment by Sigfried** [comment]
Good find. I think we need to add an environment variable secret. I'll see if I can figure out where to do that

**Comment by joeflack4** [comment]
I see the code [commented out](https://github.com/jhu-bids/TermHub/commit/3e26193b5e643b475b25692f489f5b3455095d21). You're thinking it'll let us deploy now? I was thinking more would be needed, but if that solves the deployment problem in the interim, that's good.
