### ISSUE TITLE
Drafts: Double check that they're coming through

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#579]
## Overview
1. Take a concept set, make a new draft off of it.
2. Run the refresh in TermHub.
3. See if the new draft appears. Should be 20-45 minutes. Maybe check up to 2 hours.

**Comment by Leskena2** [comment]
created 100545942 - TermHub Diabetes Test (draft) and 285304591 - TermHub (V1). Tested in TermHub Dev and Prod. both csets were visible.

**Comment by joeflack4** [comment]
Good to get confirmation on that. Thanks @Leskena2 !
