### ISSUE TITLE
UX: Add checkmarks to colored cells and fix typos

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#672]
Lisa:
> Sigfried Gold this screen shot is what I meant to send you yesterday. The orange and pink cells, should they also have a checkmark in them since I think it means the concept is present? By the way, there is a spelling error in the word "definition" in the key gray cell when you get a chance to fix it. 

<img width="1132" alt="image" src="https://github.com/jhu-bids/TermHub/assets/1586931/bbe16656-d546-4ccf-8b25-d0011e34ddb5">

**Comment by joeflack4** [comment]
Siggie:
Maybe the checkmark should go in the orange.
