### ISSUE TITLE
TermHub: Connect to static content

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#74]
## Summary
Connect to `termhub-vocab` and `termhub-csets`

**Comment by Sigfried** [comment]
@joeflack4, would you say this is already accomplished? Or should anything else be included under this issue?

**Comment by joeflack4** [comment]
@Sigfried Oh, I think this is satisfied.

Of course, we still will one day add something to `termhub-vocab`, and then we should decide if mappings (e.g. Stephanie's recent one) should go in `termhub-csets`, and if so, where. And then the git LFS. But yeah, basically we have made the static content connection.
