### ISSUE TITLE
TermHub: Connect w/ our CLIs && APIs (VSAC, Enclave)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#75]
## CLIs
ValueSet tools CLIs. want to put them on PyPi first
- [x] 1. Enclave wrangler
- [ ] 2. VSAC wrangler
- [ ] 3. Any others?

## APIs
Can connect to these via our CLIs, likely.

**Comment by Sigfried** [comment]
This is probably included in #147

**Comment by joeflack4** [comment]
Enclave wrangler is connected, but I think we ought to move enclave wrangler into a separate repo / git submodule.

**Comment by hugwuoke** [comment]
I'm pretty sure this should be included in 146 but feel free to move :)
