### ISSUE TITLE
Add concepts: Add searched concepts to comparison table

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#769]
## Overview
After searching for concepts, we need to connect that feature to the comparison table and actually let users add concepts that they've searched.

## Discussion
I (Joe) think that we could have a _concept search page_ separate from the _cset comparison page_. After adding concepts on this page, it will probably take a while until the comparison page can be updated. Most of the time will probably occur on the backend. I think we'll essentially need to create the equivalent of a draft concept set that has not yet been created in the Enclave. So I think behavior we want will involve submitting the concepts you want to add, and then you can use TermHub normally. And when the new TermHub draft cset is ready to view, a notification will pop up. When you click that, it will take you to the _cset comparison page_, where your new draft will be represented as a new column, and the new concepts will appear in the tree normally.

**Comment by Sigfried** [comment]
Done
