### ISSUE TITLE
Bug: double counting of concepts that appear multiple times

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#778]
## Overview
Some concepts appear more than once in the hierarchy which means they can be double counted in numbers such as patient totals.

## Related
- #386

**Comment by joeflack4** [comment]
IDK if this is still an issue, but if so, sounds important.

**Comment by Sigfried** [comment]
Need to add counts to top of comparison table again and then probably will have to fix this double counting

**Comment by Sigfried** [comment]
I don't think this is a problem anymore.
