### ISSUE TITLE
TermHub: One concept set (cset) record/patient count

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#78]
## Summary
What Amin wants/needs from us: a table to create and expose

We can use 2 datasets as input to transform to a new table: 
1. concept_usage_counts:  https://unite.nih.gov/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.0f440603-9d5b-43e9-adbf-f3f743f45ad7/master
    - can't use this table by itself because it has more fields than what we need
2. Johanna mentioned (* waiting on; should be ready by end of August)
    - has a table phenotype explorer. it's a pivot. not the one in the knowledge store. 
    - once it's done, they can share
    - for now, can use a table with synthetic counts. She said that Tim has constructed something like that. We could use that or create similar.

Afterwards: Send Amin a message when created

**Comment by Sigfried** [comment]
> * can't use this table by itself because it has more fields than what we need

It could be fine having more fields. There are a couple issues:
  - I think we want person_day_count instead of or in addition to total_count. 
  - Having data_partner_id (and, to a lesser degree, domain) increases the size of the result set but we can group them ourselves and might appreciate the extra data at times.

The much bigger problem

**Comment by joeflack4** [comment]
@Sigfried I'll probably hear more about this at the data liaison meeting momentarily. Just curious if by closing the issue that means (a) the new table is complete, (b) we've opted to use the existing [concept_usage_counts table](https://unite.nih.gov/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.0f440603-9d5b-43e9-adbf-f3f743f45ad7/master), or (c) we are coming up with another solution.

If (c), I think this issue should still be open. But it doesn't sound like (a) or (b) has been done either. So I'm wondering what the next steps on this issue are.

Regarding patient counts, I suppose we could simply display `20` on our side in TermHub if we get something with counts less than 20, but I imagine that's not good enough; we probably still need to do what you're articulating, though I am not familiar enough w/ this data, so idk my understanding on this issue is still pretty fuzzy overall.

**Comment by joeflack4** [comment]
[Original API request notes from Siggie's Roam Research](https://docs.google.com/document/d/1c3Kj-amtBHmJvpnX-xnKm1CIqcCbEq0Or5nIJiNST34/edit):
(I would have copy/pasted this but it wouldn't let me for some reason)
![Uploading Screen Shot 2022-07-21 at 2.16.23 PM.png…]()

**Comment by joeflack4** [comment]
Siggie's mockup from today: 
[2021-02-10-study3-design-sketches-page.pdf](https://github.com/jhu-bids/TermHub/files/9508374/2021-02-10-study3-design-sketches-page.pdf)

**Comment by joeflack4** [comment]
@Sigfried Is this done?
