### ISSUE TITLE
[TermHub & ValueSet-Tools]: Bifurcate repo

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#79]
Might need to remake issues, although there may be a way to move issues to another repository as well.

**Comment by hugwuoke** [comment]
Hmm do the issues still need to be remade 👀

**Comment by joeflack4** [comment]
@hugwuoke @Sigfried If you guys want, we could create a new empty repo for ValueSet Tools and move those issues to the new repo. And then, for the code, we'd basically checkout a TermHub commit from some time in spring 2022 and we can push that to the repo. That's the last time that ValueSet Tools existed.

Or we could maybe just close all the ValueSet Tools issues. We haven't used it in over a year and nobody's asked about it since then either. Most of what it did, TermHub and EnclaveWrangler did and more. Although I think it did have some VSAC ([Value Set Authority Center](https://vsac.nlm.nih.gov/)) stuff.
