### ISSUE TITLE
TermHub: Vocabulary management (aka, a single concept)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#81]
## Summary
Allow user to do CRUD on a single concept.
- [x] 1. UI to read and edit properties, or delete the concept version.
- [x] 2. Ability to push the concept somewhere (e.g. disk, FHIR server, enclave)

## Related
- #91

**Comment by joeflack4** [comment]
Under the context of vocabulary management on-the-whole (as opposed to a single concept), there is a project in need of such a UI: #26

**Comment by Sigfried** [comment]
@joeflack4 What is this?

**Comment by joeflack4** [comment]
@Sigfried This is the result of a discussion from some past call. I think this is related to some curator kinds of features; think Apelon.

I added a couple ideas to the issue but I'm sure there are more.

I imagine this is not a near-term issue at all because curator features are not a priority at this stage.

**Comment by hugwuoke** [comment]
I think we accomplished this!
