### ISSUE TITLE
Add window padding

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#813]
## Overview
There is currently no left/right window padding. This results in the cset comparison table appearing as if maybe there are additional columns off-screen. Could also be resolved by left/right table margin.

<img width="1143" alt="Screenshot 2024-06-20 at 11 39 18 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/a51252fd-a32a-4cca-82c8-a1861c6a7f1b">

**Comment by Sigfried** [comment]
fixed
