### ISSUE TITLE
Error: didn't expect this

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#818]
## Overview
I'm not sure what the ramifications of this error appearing, but I'm seeing it in the logs.

## Replicability
1. Go to: https://icy-ground-0416a040f.2.azurestaticapps.net/cset-comparison?codeset_ids=1000002230&codeset_ids=1000039164
2. Click: _Show stats options_
3. Under _Definition concepts_, click _Show_
  - The error appears. If you click _Unshow_ / _Show_ subsequently, it does not re-appear.
4. Under _Concepts_, click _Expand all_
  - The error appears. If you click _Collapse all_ / _Expand all_ subsequently, it appears each time for both collapse and expand.

## Additional info
<details><summary>Screenshot</summary>
<p>

<img width="1722" alt="Screenshot 2024-06-23 at 4 49 03 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/70db0448-f47a-48ed-a27b-349dd47772d7">

</p>
</details>

**Comment by Sigfried** [comment]
Seems to be fixed
