### ISSUE TITLE
TermHub: Multiple csets / concept set comparison / overlap analysis

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#82]
## Overview
Compare 2 concept sets.

## Feature list
- %'s and `n`s of concepts shared/unshared between 
- The specific concepts (ID / label) shared/unshared between
- Modes: (i) extensional, (ii) intensional
- Attach to counts in enclave (can’t export diff counts for now)
- Use for editing new csets (CSet validation and editing)

## UI details
- Tabular view: essential
- Graphical hierarchical view: [Siggie wrote](https://docs.google.com/presentation/d/1Pt3kI9OK356iUX7GqLXo55Zn7iGRDJYBaT4QkNER9Qc/edit#slide=id.g1504eacee7e_0_0): Graphical view of cset(s) based on vocab hierarchies/structures. I would guess that this one is more of a bonus feature. I would guess that this would entail looking at the an expanded tree structure, and highlighting concepts one of 3 colors: (i) in concept set A, (ii) in concept set B, (iii) in both.

## Additional info
1. [Siggie's current projects](https://docs.google.com/presentation/d/1Pt3kI9OK356iUX7GqLXo55Zn7iGRDJYBaT4QkNER9Qc/edit#slide=id.g1504eacee7e_0_0) slides
2. Some of Tanner' use cases (based on discussion w/ Siggie 2022/09/07). (I'm not sure if _ii_ or _iii_ are for multiple cset view, single cset view, or both): (i) looking at csets hierarchically, (ii) using the intensional cset rules (i.e., a code plus the three flags — descendants, mapped, exclude), (iii) and handling csets with concepts from more than one domain.

**Comment by Sigfried** [comment]
![2021-02-10-study3-design-sketches-4](https://user-images.githubusercontent.com/1586931/188942659-03703f2b-b80b-4b08-9af2-a5255a785660.jpg)

**Comment by joeflack4** [comment]
**UI details**
a. cards: I was thinking of just showing 'card' widgets which show a list of concepts, and then perhaps a list of red concepts for any that are in set 1 but not in set 2 (if comparing 2 sets), and green if in set 1 but not in set 2.
b. venn diagram
c. matrix: Siggie came up w/ this (more details in [this pdf](https://github.com/jhu-bids/TermHub/files/9522418/2021-02-10-study3-design-sketches-page.pdf)):
<img width="625" alt="Screen Shot 2022-09-07 at 8 12 00 PM" src="https://user-images.githubusercontent.com/13045020/189006520-0bf237c8-8b0b-459f-97d9-9d438024af9e.png">

**Comment by hugwuoke** [comment]
@joeflack4 if it doesn't take too much time could you see if anything here is worth keeping? if not dw.

**Comment by joeflack4** [comment]
Yeah I think this should have been closed long ago!
