### ISSUE TITLE
TermHub: Special sets of concept sets (Bundles, approved, etc)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#83]

**Comment by Sigfried** [comment]
This can be handled through the ontology api. See 0171fc7de0deb99f4dad983470b213a7324a23f9

**Comment by hugwuoke** [comment]
@Sigfried is this no longer relevant?

**Comment by joeflack4** [comment]
I'll leave this closed but I think this is one of those future, low priority issues.
