### ISSUE TITLE
TermHub: Documentation / about

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#86]
## Summary
- [ ] 1. Add a paragraph to `README.md` at root of this repository
- [ ] 2. Create an 'About' page in app and re-use paragraph from (1)

**Comment by hugwuoke** [comment]
I think this is done !

**Comment by joeflack4** [comment]
Thanks for finding so many of these unclosed ones! We've almost never had/taken the time to actually go through the project board during our regular meetings.
