### ISSUE TITLE
Bug: Refresh fails; Dropping `concept` table?

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#872]
## Overview
The DB refresh, fetch failures script, and also last night's vocab refresh all failed on a line where it is trying to drop `concept` without `CASCADE`.

## Errors
[Error log from DB refresh](https://github.com/jhu-bids/TermHub/actions/runs/10742806368/job/29796186586): `[SQL: DROP TABLE IF EXISTS n3c.concept;]`

<details><summary>More detail</summary>
<p>

```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table concept because other objects depend on it
DETAIL:  view cset_members_items_plus depends on table concept
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: DROP TABLE IF EXISTS n3c.concept;]
```

</p>
</details> 

## Sub-tasks
- [ ] 1. Why is it dropping `concept`? I don't remember that being a table we should drop during refreshes.
- [ ] 2. Fix issue
  - Probably by removing the dropping of `concept`, or adding `CASCADE`

**Comment by Sigfried** [comment]
Do you know what script it's failing in?
