### ISSUE TITLE
Sync `.env`s

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#876]
## Overview
Siggie & Joe's `.env` files are out of sync. This can create problems when updating in various places, such as the `ENV_FILE` secret on GitHub.

Probably Siggie is missing or has an incorrect `GH_LIMITED_PERSONAL_ACCESS_TOKEN` (#831). This is causing something in the refresh to fail.

**Comment by Sigfried** [comment]
Oh. I have one, but I forgot to include it last time.
