### ISSUE TITLE
TermHub: Statement of copyright?

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#88]
## Summary
Statement of copyright / from N3C or similar?

**Comment by joeflack4** [comment]
@hlehmann17 Can you give an example of what this might look like? I roughly get what this is about, but I'm not exactly sure what to write / link to or where to put it.

**Comment by hlehmann17** [comment]
I'm no expert.

One example comes from vsac.nlm.nih.gov: https://www.nlm.nih.gov/web_policies.html
It has way more information than we need, but gives us a nice menu of what to leave out.

Here's from the COKA project (https://fevir.net)
© 2022, Patent Pending. FEvIR Platform version 0.55.0 (July 11, 2022) uses [FHIR® current build](https://fevir.net/). CodeSystem Viewer version 0.27.3 (April 15, 2022). Use implies agreement to the [Acceptable Use Policy](https://fevir.net/termsofuse)

Background information: https://www.michalsons.com/blog/the-rights-to-a-database/2937

→ https://wiki.creativecommons.org/wiki/Data


OHDSI: 2022[ Observational Health Data Sciences and Informatics](https://ohdsi.org/)

**Comment by joeflack4** [comment]
I see, thanks. I generally like the very liberal MIT license. I could throw that up on GitHub and then link to that. But I'm not actually sure if something that uses the N3C API makes sense to put under that license.

Not a big deal anyhow, but at least we've got it hear on our radar.

**Comment by hugwuoke** [comment]
I think we already have a license.
