### ISSUE TITLE
Bug: Large csets won't load (after `expandAll`)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#924]
### Overview
If you are in the concept comparison page and hit "Expand All", it generally is not an issue. However, the expansion state has a memory. So if you load another concept set comparison that contains too many concepts, it will not be able to load.

### To Reproduce
1. Compare 2 small concept sets.
2. Click "expand all" (stats and options)
3. Go back to the home page / cset selection page
4. Select malignant cancer
5. Hit load csets
6. Go to the comparison page

**Comment by Sigfried** [comment]
Amazingly, recent refactor of caching and of row expand/collapse make this no longer a problem. Really amazingly, I can load Malignant Cancer with expand all turned on and it actually loads and the browser page is usable! I even downloaded csv to make sure it had really gotten all 55K concepts. Actually, with duplicate rows shown (as they are in the csv), it was more than 800K rows, which was too big for Excel to open and even trying to open it made my laptop start complaining about being out of memory.
