### ISSUE TITLE
Warning: Why is csid CSID missing?

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#927]
## Overview
http://localhost:3000/OMOPConceptSets?codeset_ids=875251048&codeset_ids=66958010

Console warning:
> Warning: Why is csid CSID missing?

**Comment by Sigfried** [comment]
Here's why:
![Image](https://github.com/user-attachments/assets/b554afcf-52d2-44c0-8207-f2efbb81fc2d)

How can there be a codeset_id in concept_ids_by_codeset_id that's not in code_sets?

**Comment by Sigfried** [comment]
Just reran `ddl-7-concept_ids_by_codeset_id.jinja.sql` and the row is still there...

It's because there are 19 codeset_ids in `concept_set_version_item` but not in `code_sets`:

![Image](https://github.com/user-attachments/assets/d520d5ec-fc33-4831-8154-5d59b59e8f16)

**Comment by Sigfried** [comment]
Fixing ddl-6-cset_members_items.jinja.sql: previously did a full outer join between concept_set_members and concept_set_version_items. Now has code_sets in there, so will leave out version_item rows where there's no associated code_set.
