### ISSUE TITLE
UX: Sorting: Restore flat (unnested) display option to allow sorting and better selection

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#929]
- [ ] #506

**Comment by joeflack4** [comment]
@Sigfried If this is not quick to do, I would put this after 'add concepts' and several bug fixes

**Comment by Sigfried** [comment]
![Image](https://github.com/user-attachments/assets/611b0db6-12c4-4f43-bb59-5c48d56fe497)

Now have a toggle button for switching between nested and unnested. The only way I could figure out to get the original sort order back after going back to nested is by reloading the whole page. A bit clunky, but it works.

I did open an issue https://github.com/jbetancur/react-data-table-component/issues/1260 to see if react-data-table-component can provide a way to do this without a reload, but not super important.

**Comment by joeflack4** [comment]
Whoa! GJ. i like the icon
