### ISSUE TITLE
Caching: Improve cache history

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#932]
## Overview
Don't know how big the individual slices are.

Would be nice, every time you put something in the cache, "you're trying to put 'x' in the cache, and it's this big, and making this slice of the cache this much bigger."

It doesn't currently save by slices. It saves the whole thing.

**Comment by joeflack4** [comment]
@Sigfried Is this done? Completed by this?:
- #934

**Comment by Sigfried** [comment]
Not exactly history in the way it was before, but `dataCacheW.getStats()` gives this with entire malignant cancer comparison in cache:

{
    "totalSize": 2417249,
    "slices": {
        "csets": {
            "totalSize": 1261,
            "itemCount": 2,
            "currentAction": {
                "items": 0,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 2,
                "sizeMB": "0.00"
            },
            "largestItems": [
                {
                    "key": "_csets",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                },
                {
                    "key": "_csets:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "0.00"
        },
        "concept-graph": {
            "totalSize": 519096,
            "itemCount": 2,
            "currentAction": {
                "items": 0,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 2,
                "sizeMB": "0.50"
            },
            "largestItems": [
                {
                    "key": "_concept-graph:⌀挡\ud819脸䀸Ϫ灆〛Xහ\u0000",
                    "sizeMB": "0.49",
                    "isCurrentAction": false
                },
                {
                    "key": "_concept-graph:⌀挡\ud819脸䀸Ϫ灆〛Xහ\u0000:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "0.50"
        },
        "whoami": {
            "totalSize": 215,
            "itemCount": 2,
            "currentAction": {
                "items": 0,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 2,
                "sizeMB": "0.00"
            },
            "largestItems": [
                {
                    "key": "_whoami",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                },
                {
                    "key": "_whoami:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "0.00"
        },
        "concepts": {
            "totalSize": 673104,
            "itemCount": 2,
            "currentAction": {
                "items": 0,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 2,
                "sizeMB": "0.64"
            },
            "largestItems": [
                {
                    "key": "_concepts",
                    "sizeMB": "0.64",
                    "isCurrentAction": false
                },
                {
                    "key": "_concepts:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "0.64"
        },
        "researchers": {
            "totalSize": 362,
            "itemCount": 2,
            "currentAction": {
                "items": 1,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 1,
                "sizeMB": "0.00"
            },
            "largestItems": [
                {
                    "key": "_researchers",
                    "sizeMB": "0.00",
                    "isCurrentAction": true
                },
                {
                    "key": "_researchers:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "0.00"
        },
        "cset_members_items": {
            "totalSize": 1223211,
            "itemCount": 2,
            "currentAction": {
                "items": 0,
                "sizeMB": "0.00"
            },
            "previousActions": {
                "items": 2,
                "sizeMB": "1.17"
            },
            "largestItems": [
                {
                    "key": "_cset_members_items",
                    "sizeMB": "1.17",
                    "isCurrentAction": false
                },
                {
                    "key": "_cset_members_items:meta",
                    "sizeMB": "0.00",
                    "isCurrentAction": false
                }
            ],
            "sizeMB": "1.17"
        }
    },
    "summary": {
        "totalItems": 12,
        "sizeMB": "2.31",
        "currentAction": {
            "items": 1,
            "sizeMB": "0.00"
        },
        "previousActions": {
            "items": 11,
            "sizeMB": "2.30"
        },
        "largestItems": [
            {
                "key": "_cset_members_items",
                "slice": "cset_members_items",
                "sizeMB": "1.17",
                "isCurrentAction": false
            },
            {
                "key": "_concepts",
                "slice": "concepts",
                "sizeMB": "0.64",
                "isCurrentAction": false
            },
            {
                "key": "_concept-graph:⌀挡\ud819脸䀸Ϫ灆〛Xහ\u0000",
                "slice": "concept-graph",
                "sizeMB": "0.49",
                "isCurrentAction": false
            },
            {
                "key": "_csets",
                "slice": "csets",
                "sizeMB": "0.00",
                "isCurrentAction": false
            },
            {
                "key": "_researchers",
                "slice": "researchers",
                "sizeMB": "0.00",
                "isCurrentAction": true
            }
        ]
    }
}

**Comment by joeflack4** [comment]
I don't totally understand what I'm looking at here but it seems like this is part of what you were going for and probably helpful!
