### ISSUE TITLE
Bug: Cset authoring: `isExcluded`, `includeDescendants`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#938]
## Overview
The details on this are fuzzy to me, but I think when a concept is added, we need some default values for these, and need to enable them to work correctly when activated/deactivated.

If you flag as excluded, and especially with includeDescendants, mark that as excluded, and all its descendants *everywhere on the page if appears multiple times*.

### UI updates
Copied from:
- #217

Should start from expression items, and show included, mapped, excluded from there. For each set of concepts related to an expression item:
- Sort by: 1) no flags, 2) `includeDescendants`, 3) `includeMapped`, 3a) include Descendants of Mapped (both flags), 4) `isExcluded`: show in red or something, same order as includes, also mark any included concepts above as excluded.
- Grouping: Visually group the concepts together, e.g. by (a) different background colors for groups of rows, like a set of rows with white background, then a set with light grey background, repeating ([example](https://support.content.office.net/en-us/media/d156448c-f88a-46f0-8578-415ac09dee46.png)), or (b) different line styles/colors on the left border of the table, like a thick line for one group, thin line for the next, repeating.

## Related
- #937 - Joe: I don't even think this issue was correctly stated. Not sure what the issue was I was trying to describe.
- #217
- #939

**Comment by Sigfried** [comment]
Basic functionality now in place. Need tests and to consider the UI ideas in this issue.

**Comment by Sigfried** [comment]
Just did a successful face test: brought up a cset comparison (http://localhost:3000/cset-comparison?codeset_ids=438533155&codeset_ids=1000032560), created a new concept set, and confirmed that the new cset expansion was identical to the expansion of the cset version expanded with the most recent vocabulary.

**Comment by Sigfried** [comment]
Would be nice to add #939 so authoring view really reflects what expansion would look like; but people don't use includeMapped very much, so, it's pretty great that it shows effects of includeDescendants and isExcluded.

**Comment by joeflack4** [comment]
Thanks Siggie!
