### ISSUE TITLE
TermHub: Consider using JQ for JSON manipulation

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#94]
- https://stackoverflow.com/questions/37668134/how-to-install-jq-on-mac-on-the-command-line
- https://stedolan.github.io/jq/manual/

**Comment by Sigfried** [comment]
I vote yes. Any objections?

I guess the next question is how and where. Did you (@joeflack4) have any particular pieces of code you were considering jq for?

**Comment by joeflack4** [comment]
@Sigfried No objections at the moment. I don't have anything particular in mind. Maybe a GitHub issue wasn't the best place to put this though. I guess we can close it. Just hopefully will remember to use it where it is useful; you'll probably get to that before me, as you have used this tool / know it better than I.
