### ISSUE TITLE
Bug: onHover err (search page)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#940]
## Overview
I didn't get to fully write down what happened to Siggie, but we were using the comparison page, then went to the search page, tried selecting from the list, and when we hovered over an option, we got a console error. And I think the page might have also went white / been unusable.

## Replicability
Haven't been able to yet.

- I think it happened (once, maybe not every time) when pasting an ID into the search box
- Happened with _[DRAFT] alcoholic hepatitis 66958010_

**Comment by Sigfried** [comment]
Fixed it last week or the week before.
