### ISSUE TITLE
Bug: Can't expand `unlinked`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#943]
## Overview
Joe: I was in a state where everything was collapsed, and 'unlinked' had 66 children. if i hit + icon, or "expand all", none of them would expand.

## Sub-tasks
- [ ] @joeflack4 Replicate
- [ ] Siggie: Fix when can replicate

**Comment by Sigfried** [comment]
Taking myself off this one until @joeflack4 replicates it. I don't think it's a bug anymore.

**Comment by joeflack4** [comment]
@Sigfried Couldn't replicate. You know, I wonder if I was just being silly and the reason it wouldn't expand is because I had the zero counts or w/e on hide, and all of the unlinked met those hide conditions.
