### ISSUE TITLE
Add concepts page: Allow sorting by any column

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#954]
## Overview
We should add sorting by any column in the table for the concept set comparison page.

## Context
_[Siggie wrote](https://github.com/jhu-bids/TermHub/commit/6b575ab83391ac9c915556773d97e2a4d5c7931e)_:
> Fixed the broken `sortFunc()` for sorting rows in comparison table (code is in `GraphState`.) TODO: allow sorting by any column in table.

**Comment by joeflack4** [comment]
@Sigfried This is for the add concepts page, not the flat view on the comparison page?

For comparison page, we have existing issue marked low priority:
- #736
