### ISSUE TITLE
Bug: URL for app state 

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#955]
## Case 1: "this link"
Example: (Asthma)
https://icy-ground-0416a040f.2.azurestaticapps.net/cset-comparison?codeset_ids=400614256&codeset_ids=419757429&codeset_ids=484619125

"Return to this work later by saving or bookmarking **this link**"

**Where broken:**
"this link" is sometimes broken, but in what way I'm not entirely sure

**What's broken:**
For example, _added concepts_ and expand/collapse state not included in link., or "show hide".

**Comment by Sigfried** [comment]
![Image](https://github.com/user-attachments/assets/25bc02f9-4427-468e-9713-cf9e2587609a)

The new copy icon on the menu copies a url to clipboard that will return you to current state, including new cset config, added concepts, expand/collapse, etc.
