### ISSUE TITLE
LLM export format

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#958]
## Overview
Make new export format for easy sharing with LLMs to get suggestions for changes

Simplify CSV download and come up w/ a workflow, you download csv, upload to claude, ask it a question

## Future
- [ ] #975

**Comment by joeflack4** [comment]
Just adding context:
I think this comes up in context of Lisa working with Harold, Richard, and another doctor on a new version of the _Mild liver disease_ cset.

Originally Siggie thought:
> Maybe waste of time for Claude to help w/ revising these csets. Look at recommendations and make by ourselves.
Could take a lot of time to get Claude to produce atlas JSON.

But there seems to be a lot of potential value here.
