### ISSUE TITLE
linkTypesForObjectTypes error

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#96]
https://github.com/jhu-bids/TermHub/blob/f3aa15a52fffaf63ad9af518abfa1c00dfd61292/enclave_wrangler/dataset_download_new_api.py#L119

Hey @joeflack4, I'm also getting an error from this call:

    ➜ curl -H "Content-type: application/json" -H "Authorization: Bearer $OTHER_TOKEN" \
            "https://unite.nih.gov/ontology-metadata/api/ontology/linkTypesForObjectTypes" --data '{
                "objectTypeVersions": {
                    "ri.ontology.main.object-type.a11d04a3-601a-45a9-9bc2-5d0e77dd512e": \
                    "00000001-9834-2acf-8327-ecb491e69b5c"
                }
            }'
    {"errorCode":"INVALID_ARGUMENT","errorName":"Default:InvalidArgument","errorInstanceId":"6b350c91-d261-4de3-93b4-acffd194c4aa","parameters":{}}

Did I give you this call or did you come up with it? I thought I had something around this working at some point.

**Comment by Sigfried** [comment]
Ok, I found a similar call in my zsh history that does work.... Oh, the problem is with one of the backslashes. I'll fix it in the code.

**Comment by Sigfried** [comment]
But I can't figure out how to run it. And that backslash is only the curl command, not in the actual code which is a python obj, not a json string.

**Comment by joeflack4** [comment]
@Sigfried We can look at this tomorrow. Probably a quick fix. I might have added the backslash just for max character per line stylistic reasons. You left this call in the docstring btw; I was just re-using that.

**Comment by hugwuoke** [comment]
@Sigfried since this seems like an error that was very specific to how Termhub functioned in Aug 2022 I felt it was ok to close this one.

**Comment by joeflack4** [comment]
Yep, this was definitely fixed long ago!
