### ISSUE TITLE
TermHub: dataset_download: /objects/OMOPConcept: Error 500

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#98]
## Overview
Got a server error. Opened a ticket: https://unite.nih.gov/workspace/issues-app/issue/ri.issues.main.issue.6a692d0a-9b32-4fac-a81b-d0c9d6b664ff

## Additional info
(1) and/or (2) may be the result of this (from the [enclave API docs](https://www.palantir.com/docs/foundry/api/ontology-resources/objects/list-objects/)): 
> This endpoint returns a maximum of 10,000 objects. After 10,000 objects have been returned and if more objects are available, attempting to load another page will result in an ObjectsExceededLimit error being returned.
> 
> Each page may be smaller or larger than the requested page size. However, it is guaranteed that if there are more results available, at least one result will be present in the response, up to 10,000 results.

**Comment by Sigfried** [comment]
this is solved by using the dataset download api instead of object ontology api (right, @joeflack4?)
